export default {
  "01_START_HERE": "1. Start Here",
  "02_embeddings_intro": "2. Embeddings Intro",
  "03_paraphrase_mining_intro": "3. Paraphrase Mining Intro",
  "04_semantic_search_intro": "4. Semantic Search Intro",
  "05-embeddings": "Overview",
  "05_semantic_textual_similarity_intro": "6. Semantic Textual Similarity Intro",
  "06_sentence_transformer_intro": "7. Sentence Transformer Intro",
  "07_sparse_encoder_intro": "8. Sparse Encoder Intro",
  "08_QUICKSTART": "9. Quickstart",
  "09_embedding_comparison": "10. Embedding Comparison",
  "10_huggingface_embeddings": "11. Hugging Face Embeddings",
  "11_openai_embeddings": "12. OpenAI Embeddings",
  "12_semantic_similarity": "13. Semantic Similarity",
  "13_vector_database_demo": "14. Vector Database Demo",
}
