export default {
  "32-cheatsheets": "1. Cheatsheets",
  cloud: "2. Cloud",
  "config-management": "3. Config Management",
  databases: "4. Databases",
  "devops-architecture": "5. Devops Architecture",
  "devops-interviews": "6. Devops Interviews",
  docker: "7. Docker",
  git: "8. Git",
  "github-actions": "9. Github Actions",
  "github-cli": "10. Github Cli",
  jenkins: "11. Jenkins",
  k8s: "12. K8s",
  linux: "13. Linux",
  monitoring: "14. Monitoring",
  networking: "15. Networking",
  "shell-scripting": "16. Shell Scripting",
  "system-design": "17. System Design",
}
