export default {
  "32-cheatsheets": "Overview",
  "ai-ml": "2. Ai Ml",
  cloud: "3. Cloud",
  "config-management": "4. Config Management",
  databases: "5. Databases",
  "devops-architecture": "6. Devops Architecture",
  "devops-interviews": "7. Devops Interviews",
  docker: "8. Docker",
  git: "9. Git",
  "github-actions": "10. Github Actions",
  "github-cli": "11. Github Cli",
  jenkins: "12. Jenkins",
  k8s: "13. K8s",
  linux: "14. Linux",
  monitoring: "15. Monitoring",
  networking: "16. Networking",
  "shell-scripting": "17. Shell Scripting",
  "system-design": "18. System Design",
}
