export default {
  "32-cheatsheets": "1. Cheatsheets",
  cloud: "2. Cloud",
  "config-management": "3. Config Management",
  databases: "4. Databases",
  "interview-prep": "5. Interview Prep",
  docker: "6. Docker",
  git: "7. Git",
  "github-actions": "8. Github Actions",
  "github-cli": "9. Github Cli",
  jenkins: "10. Jenkins",
  k8s: "11. K8s",
  linux: "12. Linux",
  monitoring: "13. Monitoring",
  networking: "14. Networking",
  "shell-scripting": "15. Shell Scripting",
  "system-design": "16. System Design",
}
