export default {
  "DataFrames-I": "1. Dataframes I",
  "DataFrames-II": "2. Dataframes Ii",
  "DataFrames-III": "3. Dataframes Iii",
  "Pandas-101-Data-Cleaning-in-Pandas": "4. Pandas 101 Data Cleaning In Pandas",
  "Pandas-101-Exploratory-Data-Analysis-in-Pandas": "5. Pandas 101 Exploratory Data Analysis In Pandas",
  "Pandas-101-Filtering-and-Ordering-in-Pandas": "6. Pandas 101 Filtering And Ordering In Pandas",
  "Pandas-101-Group-by-and-Aggregating-in-Pandas": "7. Pandas 101 Group By And Aggregating In Pandas",
  "Pandas-101-Indexing-in-Pandas": "8. Pandas 101 Indexing In Pandas",
  "Pandas-101-Merge,-Join,-and-Concatenate-in-Pandas": "9. Pandas 101 Merge, Join, And Concatenate In Pandas",
  "Pandas-101-Pandas-Series-and-Dataframes": "10. Pandas 101 Pandas Series And Dataframes",
  "Pandas-101-Reading-in-Files": "11. Pandas 101 Reading In Files",
  "Pandas-101-Visualizing-Data-in-Pandas": "12. Pandas 101 Visualizing Data In Pandas",
  "pandas-numpy-lessons": "13. Pandas NumPy Lessons",
}
