export default {
  "index": {
    "title": "Home"
  },
  "00-course-setup": "1. Course Setup",
  "01-python": "2. Python",
  "02-data-science": "3. Data Science",
  "03-maths": "4. Maths",
  "04-token": "5. Token",
  "05-embeddings": "6. Embeddings",
  "06-neural-networks": "7. Neural Networks",
  "07-vector-databases": "8. Vector Databases",
  "08-rag": "9. Rag",
  "09-mlops": "10. Mlops",
  "10-specializations": "11. Specializations",
  "11-prompt-engineering": "12. Prompt Engineering",
  "12-llm-finetuning": "13. Llm Finetuning",
  "13-multimodal": "14. Multimodal",
  "14-local-llms": "15. Local Llms",
  "15-ai-agents": "16. Ai Agents",
  "16-model-evaluation": "17. Model Evaluation",
  "17-debugging-troubleshooting": "18. Debugging Troubleshooting",
  "18-low-code-ai-tools": "19. Low Code Ai Tools",
  "19-ai-safety-redteaming": "20. Ai Safety Redteaming",
  "20-real-time-streaming": "21. Real Time Streaming",
  "21-quizzes": "22. Quizzes",
  "22-references": "23. References",
  "23-glossary": "24. Glossary",
  "24-advanced-deep-learning": "25. Advanced Deep Learning",
  "25-reinforcement-learning": "26. Reinforcement Learning",
  "26-time-series-analysis": "27. Time Series Analysis",
  "27-causal-inference": "28. Causal Inference",
  "28-practical-data-science": "29. Practical Data Science",
  "29-ai-hardware-llm-validation": "30. Ai Hardware Llm Validation",
  "30-inference-optimization": "31. Inference Optimization",
  "31-ai-powered-dev-tools": "32. Ai Powered Dev Tools",
  "32-cheatsheets": "33. Cheatsheets",
  "33-roadmaps": "34. Roadmaps",
  app: "35. App",
}
