export default {
  "01_START_HERE": "1. Start Here",
  "02_dataset_preparation": "2. Dataset Preparation",
  "03_supervised_finetuning": "3. Supervised Fine-tuning",
  "04_lora_basics": "4. LoRA Basics",
  "05_qlora_efficient": "5. QLoRA Efficient",
  "06_dpo_alignment": "6. Dpo Alignment",
  "07_evaluation": "7. Evaluation",
  "08_deployment": "8. Deployment",
  "09_grpo_reasoning_training": "9. Grpo Reasoning Training",
  "10_unsloth_fast_finetuning": "10. Unsloth Fast Fine-tuning",
  "11_quantization_gptq_awq": "11. Quantization Gptq Awq",
  "12-llm-finetuning": "12. LLM Fine-tuning",
  "12_rlhf_constitutional_ai": "13. Rlhf Constitutional AI",
}
