export default {
  "mooreslaw-tutorial": "1. Mooreslaw Tutorial",
  pairing: "2. Pairing",
  "save-load-arrays": "3. Save Load Arrays",
  "tutorial-air-quality-analysis": "4. Tutorial Air Quality Analysis",
  "tutorial-deep-learning-on-mnist": "5. Tutorial Deep Learning On Mnist",
  "tutorial-deep-reinforcement-learning-with-pong-from-pixels": "6. Tutorial Deep Reinforcement Learning With Pong From Pixels",
  "tutorial-ma": "7. Tutorial Ma",
  "tutorial-nlp-from-scratch": "8. Tutorial Nlp From Scratch",
  "tutorial-plotting-fractals": "9. Tutorial Plotting Fractals",
  "tutorial-static_equilibrium": "10. Tutorial Static Equilibrium",
  "tutorial-style-guide": "11. Tutorial Style Guide",
  "tutorial-svd": "12. Tutorial Svd",
  "tutorial-x-ray-image-processing": "13. Tutorial X Ray Image Processing",
}
