export default {
  "01_START_HERE": "1. Start Here",
  "02_gan_mathematics": "2. GAN Mathematics",
  "03_wgan_theory_implementation": "3. Wgan Theory Implementation",
  "04_variational_autoencoders_advanced": "4. Variational Autoencoders Advanced",
  "05_neural_ode": "5. Neural Ode",
  "06_info_gan": "6. Info GAN",
  "07_vision_transformers": "7. Vision Transformers",
  "08_hierarchical_vae": "8. Hierarchical VAE",
  "09_conditional_gan": "9. Conditional GAN",
  "10_vq_vae": "10. Vq VAE",
  "11_normalizing_flows": "11. Normalizing Flows",
  "12_diffusion_models": "12. Diffusion Models",
  "13_bert_architecture": "13. Bert Architecture",
  "14_gpt_architecture": "14. GPT Architecture",
  "15_efficient_transformers": "15. Efficient Transformers",
  "16_graph_neural_networks": "16. Graph Neural Networks",
  "17_maml_meta_learning": "17. Maml Meta Learning",
  "18_prototypical_networks": "18. Prototypical Networks",
  "19_neural_radiance_fields": "19. Neural Radiance Fields",
  "20_stylegan": "20. Stylegan",
  "21_contrastive_learning": "21. Contrastive Learning",
  "22_adversarial_robustness": "22. Adversarial Robustness",
  "23_knowledge_distillation": "23. Knowledge Distillation",
  "24_point_cloud_networks": "25. Point Cloud Networks",
  "25_cyclegan": "26. Cyclegan",
  "26_progressive_gan": "27. Progressive GAN",
  "27_model_interpretability": "28. Model Interpretability",
  "28_curriculum_learning": "29. Curriculum Learning",
  "29_continual_learning": "30. Continual Learning",
  "30_neural_architecture_search": "31. Neural Architecture Search",
  "31_attention_mechanisms": "32. Attention Mechanisms",
  "32_memory_networks": "33. Memory Networks",
  "33_capsule_networks": "34. Capsule Networks",
  "34_score_based_models": "35. Score Based Models",
  "35_energy_based_models": "36. Energy Based Models",
  "36_mixture_of_experts": "37. Mixture Of Experts",
  "37_implicit_neural_representations": "38. Implicit Neural Representations",
  "38_gaussian_processes": "39. Gaussian Processes",
  "39_bayesian_neural_networks": "40. Bayesian Neural Networks",
}
