export default {
  approximate_nearest_neighbors: "1. Approximate Nearest Neighbors",
  plot_caching_nearest_neighbors: "2. Plot Caching Nearest Neighbors",
  plot_classification: "3. Plot Classification",
  plot_digits_kde_sampling: "4. Plot Digits Kde Sampling",
  plot_kde_1d: "5. Plot Kde 1d",
  plot_lof_novelty_detection: "6. Plot Lof Novelty Detection",
  plot_lof_outlier_detection: "7. Plot Lof Outlier Detection",
  plot_nca_classification: "8. Plot Nca Classification",
  plot_nca_dim_reduction: "9. Plot Nca Dim Reduction",
  plot_nca_illustration: "10. Plot Nca Illustration",
  plot_nearest_centroid: "11. Plot Nearest Centroid",
  plot_regression: "12. Plot Regression",
  plot_species_kde: "13. Plot Species Kde",
}
