export default {
  plot_confusion_matrix: "1. Plot Confusion Matrix",
  plot_cost_sensitive_learning: "2. Plot Cost Sensitive Learning",
  plot_cv_indices: "3. Plot Cv Indices",
  plot_cv_predict: "4. Plot Cv Predict",
  plot_det: "5. Plot Det",
  plot_grid_search_digits: "6. Plot Grid Search Digits",
  plot_grid_search_refit_callable: "7. Plot Grid Search Refit Callable",
  plot_grid_search_stats: "8. Plot Grid Search Stats",
  plot_grid_search_text_feature_extraction: "9. Plot Grid Search Text Feature Extraction",
  plot_learning_curve: "10. Plot Learning Curve",
  plot_likelihood_ratios: "11. Plot Likelihood Ratios",
  plot_multi_metric_evaluation: "12. Plot Multi Metric Evaluation",
  plot_nested_cross_validation_iris: "13. Plot Nested Cross Validation Iris",
  plot_permutation_tests_for_classification: "14. Plot Permutation Tests For Classification",
  plot_precision_recall: "15. Plot Precision Recall",
  plot_randomized_search: "16. Plot Randomized Search",
  plot_roc: "17. Plot Roc",
  plot_roc_crossval: "18. Plot Roc Crossval",
  plot_successive_halving_heatmap: "19. Plot Successive Halving Heatmap",
  plot_successive_halving_iterations: "20. Plot Successive Halving Iterations",
  plot_train_error_vs_test_error: "21. Plot Train Error Vs Test Error",
  plot_tuned_decision_threshold: "22. Plot Tuned Decision Threshold",
  plot_underfitting_overfitting: "23. Plot Underfitting Overfitting",
}
