import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration.
 *
 * In the original Nextra site the sidebar order and titles were defined in
 * `next-docs/src/app/_meta.ts`. The migration script (`scripts/migrate-from-nextra.mjs`)
 * translates that into Docusaurus conventions:
 *   - each chapter folder gets a `_category_.json` (label + position)
 *   - each doc gets `sidebar_position` front matter
 *
 * We therefore use the fully autogenerated sidebar, which reads those files and
 * reproduces the exact ordering from `_meta.ts` without hand-maintaining a list.
 */
const sidebars: SidebarsConfig = {
  curriculumSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
