export default {
  "01_linear_regression": "1. Linear Regression",
  "02_gradient_descent": "2. Gradient Descent",
  "03_locally_weighted_regression": "3. Locally Weighted Regression",
  "04_logistic_regression": "4. Logistic Regression",
  "05_generative_models": "5. Generative Models",
  "06_svm": "6. Svm",
  "07_regularization": "7. Regularization",
  "08_learning_theory": "8. Learning Theory",
  "09_decision_trees": "9. Decision Trees",
  "10_neural_networks_basics": "10. Neural Networks Basics",
  "11_neural_networks_advanced": "11. Neural Networks Advanced",
  "12_ml_strategy": "12. Ml Strategy",
  "13_clustering": "13. Clustering",
  "14_dimensionality_reduction": "14. Dimensionality Reduction",
  "15_reinforcement_learning": "15. Reinforcement Learning",
  CS229_PRACTICE: "16. Cs229 Practice",
  X01_anomaly_detection: "17. X01 Anomaly Detection",
  X02_recommender_systems: "18. X02 Recommender Systems",
  course: "19. Course",
}
