export default {
  "01_probability_fundamentals": "1. Probability Fundamentals",
  "02_generative_models": "2. Generative Models",
  "03_gaussian_models": "3. Gaussian Models",
  "04_bayesian_statistics": "4. Bayesian Statistics",
  "05_linear_logistic_regression": "5. Linear Logistic Regression",
  "06_sparse_linear_models": "6. Sparse Linear Models",
  "07_kernels_gaussian_processes": "7. Kernels Gaussian Processes",
  "08_graphical_models": "8. Graphical Models",
  "09_hidden_markov_models": "9. Hidden Markov Models",
  "10_mcmc_sampling": "10. Mcmc Sampling",
  "11_mixture_models_em": "11. Mixture Models Em",
  "12_dimensionality_reduction": "12. Dimensionality Reduction",
  "13_clustering": "13. Clustering",
}
