export default {
  plot_anomaly_comparison: "1. Plot Anomaly Comparison",
  plot_display_object_visualization: "2. Plot Display Object Visualization",
  plot_estimator_representation: "3. Plot Estimator Representation",
  plot_isotonic_regression: "4. Plot Isotonic Regression",
  plot_johnson_lindenstrauss_bound: "5. Plot Johnson Lindenstrauss Bound",
  plot_kernel_approximation: "6. Plot Kernel Approximation",
  plot_kernel_ridge_regression: "7. Plot Kernel Ridge Regression",
  plot_metadata_routing: "8. Plot Metadata Routing",
  plot_multilabel: "9. Plot Multilabel",
  plot_multioutput_face_completion: "10. Plot Multioutput Face Completion",
  plot_outlier_detection_bench: "11. Plot Outlier Detection Bench",
  plot_partial_dependence_visualization_api: "12. Plot Partial Dependence Visualization API",
  plot_pipeline_display: "13. Plot Pipeline Display",
  plot_roc_curve_visualization_api: "14. Plot Roc Curve Visualization API",
  plot_set_output: "15. Plot Set Output",
}
