export default {
  "01_vectors_and_linear_combinations": "1. Vectors And Linear Combinations",
  "02_linear_transformations_and_matrices": "2. Linear Transformations And Matrices",
  "03_matrix_multiplication_composition": "3. Matrix Multiplication Composition",
  "04_determinants": "4. Determinants",
  "05_eigenvalues_eigenvectors": "5. Eigenvalues Eigenvectors",
  "06_inverse_matrices_and_systems": "6. Inverse Matrices And Systems",
  "07_dot_products_and_duality": "7. Dot Products And Duality",
  "08_cross_products": "8. Cross Products",
  "09_change_of_basis": "9. Change Of Basis",
  "10_three_dimensional_transformations": "10. Three Dimensional Transformations",
  "12_cramers_rule": "11. Cramers Rule",
  "13_quick_eigenvalue_trick": "12. Quick Eigenvalue Trick",
  "16_abstract_vector_spaces": "13. Abstract Vector Spaces",
  "linear-algebra": "14. Linear Algebra",
}
