export default {
  "apply-specific-stash-from-multiple-stashes": "1. Apply Specific Stash From Multiple Stashes",
  "checkout-single-file-from-another-branch": "2. Checkout Single File From Another Branch",
  "cherry-pick-specific-commit": "3. Cherry Pick Specific Commit",
  "convert-remote-from-https-to-ssh": "4. Convert Remote From Https To Ssh",
  "create-an-annotated-tag": "5. Create An Annotated Tag",
  "fix-repository-with-unrelated-histories": "6. Fix Repository With Unrelated Histories",
  "merge-feature-branch-and-delete": "7. Merge Feature Branch And Delete",
  "merge-repositories-preserving-both-histories": "8. Merge Repositories Preserving Both Histories",
  "rebase-branch-with-reversed-commit-order": "9. Rebase Branch With Reversed Commit Order",
  "rebase-feature-branch": "10. Rebase Feature Branch",
  "rebase-feature-branch-onto-correct-base": "11. Rebase Feature Branch Onto Correct Base",
  "recover-lost-commits-from-detached-head": "12. Recover Lost Commits From Detached Head",
  "remove-file-from-entire-git-history": "13. Remove File From Entire Git History",
  "remove-last-commit-and-discard-changes": "14. Remove Last Commit And Discard Changes",
  "restore-file-to-previous-version": "15. Restore File To Previous Version",
  "shallow-clone-limited-to-latest-commit": "16. Shallow Clone Limited To Latest Commit",
  "stage-only-specific-files": "17. Stage Only Specific Files",
  "stash-work-fix-bug-restore-and-update": "18. Stash Work Fix Bug Restore And Update",
  "stash-work-fix-bug-resume": "19. Stash Work Fix Bug Resume",
  "undo-commits-but-keep-changes": "20. Undo Commits But Keep Changes",
  "update-submodule-to-latest-commit": "21. Update Submodule To Latest Commit",
  "view-unique-commits-between-branch-and-origin": "22. View Unique Commits Between Branch And Origin",
}
