export default {
  "01_START_HERE": "1. Start Here",
  "02_hardware_validation": "2. Hardware Validation",
  "03_kernel_validation": "3. Kernel Validation",
  "04_framework_validation": "4. Framework Validation",
  "05_model_performance_validation": "5. Model Performance Validation",
  "06_e2e_pipeline_validation": "6. E2e Pipeline Validation",
  "07_distributed_training_validation": "7. Distributed Training Validation",
  "08_datacenter_validation": "8. Datacenter Validation",
  "09_regression_release_validation": "9. Regression Release Validation",
  "10_benchmarking_industry": "10. Benchmarking Industry",
  "11_lab_01_hardware_validation": "11. Lab 01 Hardware Validation",
  "12_lab_02_kernel_validation": "12. Lab 02 Kernel Validation",
  "13_lab_03_model_performance": "13. Lab 03 Model Performance",
  "14_lab_04_regression_suite": "14. Lab 04 Regression Suite",
  "15_lab_05_distributed_training": "15. Lab 05 Distributed Training",
  "16_lab_06_framework_validation": "16. Lab 06 Framework Validation",
  "17_lab_07_gpgpu_backends": "17. Lab 07 Gpgpu Backends",
  "18_lab_08_benchmarking": "18. Lab 08 Benchmarking",
  "29-ai-hardware-llm-validation": "Overview",
}
