export default {
  "Apple-Health-Data": "1. Apple Health Data",
  "DataFrames-1": "2. Dataframes 1",
  "DataFrames-2": "3. Dataframes 2",
  "DataFrames-3": "4. Dataframes 3",
  "Electronic-Production-India": "5. Electronic Production India",
  GroupBy: "6. Groupby",
  "Input-and-Output": "7. Input And Output",
  "Merge,-Join-and-Concat": "8. Merge, Join And Concat",
  Multindex: "9. Multindex",
  "Options-and-Settings": "10. Options And Settings",
  "Pandas-101-Data-Cleaning-in-Pandas": "11. Pandas 101 Data Cleaning In Pandas",
  "Pandas-101-Exploratory-Data-Analysis-in-Pandas": "12. Pandas 101 Exploratory Data Analysis In Pandas",
  "Pandas-101-Filtering-and-Ordering-in-Pandas": "13. Pandas 101 Filtering And Ordering In Pandas",
  "Pandas-101-Group-by-and-Aggregating-in-Pandas": "14. Pandas 101 Group By And Aggregating In Pandas",
  "Pandas-101-Indexing-in-Pandas": "15. Pandas 101 Indexing In Pandas",
  "Pandas-101-Merge,-Join,-and-Concatenate-in-Pandas": "16. Pandas 101 Merge, Join, And Concatenate In Pandas",
  "Pandas-101-Pandas-Series-and-Dataframes": "17. Pandas 101 Pandas Series And Dataframes",
  "Pandas-101-Reading-in-Files": "18. Pandas 101 Reading In Files",
  "Pandas-101-Visualizing-Data-in-Pandas": "19. Pandas 101 Visualizing Data In Pandas",
  Panels: "20. Panels",
  Production_India_Plotly: "21. Production India Plotly",
  Read_CSV: "22. Read Csv",
  Series: "23. Series",
  "TN-Population": "24. Tn Population",
  Test: "25. Test",
  Untitled: "26. Untitled",
  Visualization: "27. Visualization",
  "Working-with-Date-and-Time": "28. Working With Date And Time",
  "Working-with-Text-Data": "29. Working With Text Data",
  "pyplot-maps": "30. Pyplot Maps",
}
