export default {
  "01_START_HERE": "1. Start Here",
  "02_intro": "2. Intro",
  "03_tokenizers_quickstart": "3. Tokenizers Quickstart",
  "04-token": "4. Token",
  "04_tokenizers_training": "5. Tokenizers Training",
  "05_advanced_training_methods": "6. Advanced Training Methods",
  "06_production_guide": "7. Production Guide",
  "07_tokenizer_comparison": "8. Tokenizer Comparison",
  "08_integration_guide": "9. Integration Guide",
  "09_pipeline_components": "10. Pipeline Components",
  "10_huggingface_tokenizers_guide": "11. Huggingface Tokenizers Guide",
  "11_sentencepiece_example": "12. Sentencepiece Example",
  "12_tiktoken_example": "13. Tiktoken Example",
  "13_token_exercises": "14. Token Exercises",
  "14_token_exploration": "15. Token Exploration",
  README_TIKTOKEN: "16. Readme Tiktoken",
  README_TOKENIZERS: "17. Readme Tokenizers",
}
