export default {
  "01_START_HERE": "1. Start Here",
  "02_intro": "2. Intro",
  "03_tokenizers_quickstart": "3. Tokenizers Quickstart",
  "04_tokenizers_training": "4. Tokenizers Training",
  "05_advanced_training_methods": "5. Advanced Training Methods",
  "06_production_guide": "6. Production Guide",
  "07_tokenizer_comparison": "7. Tokenizer Comparison",
  "08_integration_guide": "8. Integration Guide",
  "09_pipeline_components": "9. Pipeline Components",
  "10_huggingface_tokenizers_guide": "10. Huggingface Tokenizers Guide",
  "11_sentencepiece_example": "11. Sentencepiece Example",
  "12_tiktoken_example": "12. Tiktoken Example",
  "13_token_exercises": "13. Token Exercises",
  "14_token_exploration": "14. Token Exploration",
  README_TIKTOKEN: "15. Readme Tiktoken",
  README_TOKENIZERS: "16. Readme Tokenizers",
}
