export default {
  "configmap-reload-with-sidecar": "1. Configmap Reload With Sidecar",
  "crashing-misconfigured-pod": "2. Crashing Misconfigured Pod",
  "crd-schema-validation": "3. Crd Schema Validation",
  "create-namespace": "4. Create Namespace",
  "cronjob-schedule-misconfiguration": "5. Cronjob Schedule Misconfiguration",
  "custom-resource-definition-setup": "6. Custom Resource Definition Setup",
  "dns-based-service-discovery": "7. Dns Based Service Discovery",
  "dynamic-volume-expansion": "8. Dynamic Volume Expansion",
  "fix-job-with-serviceaccount-and-rbac-permission-issues": "9. Fix Job With Serviceaccount And Rbac Permission Issues",
  "image-pull-backoff-secrets": "10. Image Pull Backoff Secrets",
  "implement-statefulset-with-stable-dns": "11. Implement Statefulset With Stable Dns",
  "job-failure": "12. Job Failure",
  "multi-key-configmap": "13. Multi Key Configmap",
  "multi-tenant-namespace-isolation": "14. Multi Tenant Namespace Isolation",
  "oomkilled-pod-analysis-fix": "15. Oomkilled Pod Analysis Fix",
  "pod-viewer-access": "16. Pod Viewer Access",
  "pod-with-readiness-probe": "17. Pod With Readiness Probe",
  "pod-with-resource-limits": "18. Pod With Resource Limits",
  "secure-internal-service-communication": "19. Secure Internal Service Communication",
  "storageclass-and-pvc-expansion": "20. Storageclass And Pvc Expansion",
  "traffic-splitting-with-native-kubernetes": "21. Traffic Splitting With Native Kubernetes",
}
