export default {
  "01_essence_of_calculus": "1. Essence Of Calculus",
  "02_paradox_of_derivative": "2. Paradox Of Derivative",
  "03_derivative_formulas": "3. Derivative Formulas",
  "04_chain_product_rules": "4. Chain Product Rules",
  "05_exponential_derivatives": "5. Exponential Derivatives",
  "06_implicit_differentiation": "6. Implicit Differentiation",
  "07_limits_lhopital": "7. Limits Lhopital",
  "08_integration_fundamental_theorem": "8. Integration Fundamental Theorem",
  "09_area_and_slope": "9. Area And Slope",
  "10_higher_order_derivatives": "10. Higher Order Derivatives",
  "11_taylor_series": "11. Taylor Series",
  "12_what_makes_e_special": "12. What Makes E Special",
  calculus: "13. Calculus",
}
