export default {
  plot_adjusted_for_chance_measures: "1. Plot Adjusted For Chance Measures",
  plot_affinity_propagation: "2. Plot Affinity Propagation",
  plot_agglomerative_clustering_metrics: "3. Plot Agglomerative Clustering Metrics",
  plot_agglomerative_dendrogram: "4. Plot Agglomerative Dendrogram",
  plot_birch_vs_minibatchkmeans: "5. Plot Birch Vs Minibatchkmeans",
  plot_bisect_kmeans: "6. Plot Bisect Kmeans",
  plot_cluster_comparison: "7. Plot Cluster Comparison",
  plot_coin_segmentation: "8. Plot Coin Segmentation",
  plot_coin_ward_segmentation: "9. Plot Coin Ward Segmentation",
  plot_dbscan: "10. Plot Dbscan",
  plot_dict_face_patches: "11. Plot Dict Face Patches",
  plot_digits_agglomeration: "12. Plot Digits Agglomeration",
  plot_digits_linkage: "13. Plot Digits Linkage",
  plot_face_compress: "14. Plot Face Compress",
  plot_feature_agglomeration_vs_univariate_selection: "15. Plot Feature Agglomeration Vs Univariate Selection",
  plot_hdbscan: "16. Plot Hdbscan",
  plot_inductive_clustering: "17. Plot Inductive Clustering",
  plot_kmeans_assumptions: "18. Plot Kmeans Assumptions",
  plot_kmeans_digits: "19. Plot Kmeans Digits",
  plot_kmeans_plusplus: "20. Plot Kmeans Plusplus",
  plot_kmeans_silhouette_analysis: "21. Plot Kmeans Silhouette Analysis",
  plot_kmeans_stability_low_dim_dense: "22. Plot Kmeans Stability Low Dim Dense",
  plot_linkage_comparison: "23. Plot Linkage Comparison",
  plot_mean_shift: "24. Plot Mean Shift",
  plot_mini_batch_kmeans: "25. Plot Mini Batch Kmeans",
  plot_optics: "26. Plot Optics",
  plot_segmentation_toy: "27. Plot Segmentation Toy",
  plot_ward_structured_vs_unstructured: "28. Plot Ward Structured Vs Unstructured",
}
