export default {
  "1-Introduction": "1. Introduction",
  "2-Working-With-Data": "2. Working With Data",
  "3-Data-Visualization": "3. Data Visualization",
  "4-Data-Science-Lifecycle": "4. Data Science Lifecycle",
  "5-Data-Science-In-Cloud": "5. Data Science In Cloud",
  "6-Data-Science-In-Wild": "6. Data Science In Wild",
  CODE_OF_CONDUCT: "7. Code Of Conduct",
  CONTRIBUTING: "8. Contributing",
  SECURITY: "9. Security",
  SUPPORT: "10. Support",
  TRANSLATIONS: "11. Translations",
  docs: "12. Docs",
  "for-teachers": "13. For Teachers",
  "quiz-app": "14. Quiz App",
  sketchnotes: "15. Sketchnotes",
}
