export default {
  "01-microsoft-course": "1. Microsoft Course",
  "1-Introduction": "2. Introduction",
  "2-Working-With-Data": "3. Working With Data",
  "3-Data-Visualization": "4. Data Visualization",
  "4-Data-Science-Lifecycle": "5. Data Science Lifecycle",
  "5-Data-Science-In-Cloud": "6. Data Science In Cloud",
  "6-Data-Science-In-Wild": "7. Data Science In Wild",
  CODE_OF_CONDUCT: "8. Code Of Conduct",
  CONTRIBUTING: "9. Contributing",
  SECURITY: "10. Security",
  SUPPORT: "11. Support",
  docs: "13. Docs",
  "for-teachers": "14. For Teachers",
  "quiz-app": "15. Quiz App",
  sketchnotes: "16. Sketchnotes",
}
