export default {
  "01_introduction_learning_theory": "1. Introduction Learning Theory",
  "02_concentration_inequalities": "2. Concentration Inequalities",
  "03_rademacher_complexity": "3. Rademacher Complexity",
  "04_pac_bayes_theory": "4. Pac Bayes Theory",
  "05_neural_tangent_kernel": "5. Neural Tangent Kernel",
  "06_variational_inference": "6. Variational Inference",
  "07_bayesian_nonparametrics": "7. Bayesian Nonparametrics",
  "08_expectation_maximization": "8. Expectation Maximization",
  "09_gradient_descent_convergence": "9. Gradient Descent Convergence",
  "10_state_space_models": "10. State Space Models",
  "11_copula_theory": "11. Copula Theory",
  "12_determinantal_point_processes": "12. Determinantal Point Processes",
  "13_johnson_lindenstrauss": "13. Johnson Lindenstrauss",
  "14_duality_theory": "14. Duality Theory",
  "15_conjugate_gradients": "15. Conjugate Gradients",
  "16_matrix_concentration_inequalities": "16. Matrix Concentration Inequalities",
}
