export default {
  "5-scikit-learn": "1. Scikit Learn",
  applications: "2. Applications",
  bicluster: "3. Bicluster",
  calibration: "4. Calibration",
  classification: "5. Classification",
  cluster: "6. Cluster",
  compose: "7. Compose",
  covariance: "8. Covariance",
  cross_decomposition: "9. Cross Decomposition",
  datasets: "10. Datasets",
  decomposition: "11. Decomposition",
  developing_estimators: "12. Developing Estimators",
  ensemble: "13. Ensemble",
  feature_selection: "14. Feature Selection",
  frozen: "15. Frozen",
  gaussian_process: "16. Gaussian Process",
  impute: "17. Impute",
  inspection: "18. Inspection",
  kernel_approximation: "19. Kernel Approximation",
  linear_model: "20. Linear Model",
  manifold: "21. Manifold",
  miscellaneous: "22. Miscellaneous",
  mixture: "23. Mixture",
  model_selection: "24. Model Selection",
  multiclass: "25. Multiclass",
  multioutput: "26. Multioutput",
  neighbors: "27. Neighbors",
  neural_networks: "28. Neural Networks",
  preprocessing: "29. Preprocessing",
  release_highlights: "30. Release Highlights",
  semi_supervised: "31. Semi Supervised",
  svm: "32. Svm",
  text: "33. Text",
  tree: "34. Tree",
}
