#!/usr/bin/env python3
"""Create remaining MLOps notebooks (04-07)"""

import json

def nb(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.11.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

def md(text):
    return {"cell_type": "markdown", "metadata": {}, "source": [line + "\n" for line in text.split("\n")]}

def code(text):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [line + "\n" for line in text.split("\n")]}

def save_notebook(filename, cells):
    with open(filename, 'w') as f:
        json.dump(nb(cells), f, indent=2)

# Notebook 04: Docker for ML
notebook_04 = [
    md("# Containerizing ML Applications with Docker\n\n## 🎯 Learning Objectives\n\n- Understand Docker concepts\n- Build Docker images for ML apps\n- Create multi-stage builds\n- Optimize image size\n- Use Docker Compose for multi-container apps\n\n## Why Docker?\n\n**Problems without Docker:**\n- \"Works on my machine\" syndrome\n- Dependency conflicts\n- Environment inconsistencies\n- Difficult deployment\n\n**Docker benefits:**\n- Consistent environments\n- Easy deployment\n- Isolation\n- Reproducibility\n- Scalability"),
    
    md("## Docker Basics\n\n### Key Concepts\n\n- **Image**: Blueprint for containers (like a class)\n- **Container**: Running instance of an image (like an object)\n- **Dockerfile**: Instructions to build an image\n- **Registry**: Storage for images (Docker Hub, ECR, etc.)\n\n### Basic Commands\n\n```bash\n# Build image\ndocker build -t myapp:v1 .\n\n# Run container\ndocker run -p 8000:8000 myapp:v1\n\n# List containers\ndocker ps\n\n# Stop container\ndocker stop <container_id>\n\n# Remove container\ndocker rm <container_id>\n```"),
    
    md("## Simple ML API Dockerfile"),
    
    code("# Create a simple Dockerfile\ndockerfile_content = '''FROM python:3.11-slim\n\nWORKDIR /app\n\n# Copy requirements\nCOPY requirements.txt .\n\n# Install dependencies\nRUN pip install --no-cache-dir -r requirements.txt\n\n# Copy application\nCOPY . .\n\n# Expose port\nEXPOSE 8000\n\n# Run application\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n'''\n\n# Save to file (in practice)\nprint(\"Dockerfile created:\")\nprint(dockerfile_content)"),
    
    md("## Requirements File"),
    
    code("requirements = '''fastapi==0.104.1\nuvicorn[standard]==0.24.0\nscikit-learn==1.3.2\njoblib==1.3.2\nnumpy==1.26.2\npydantic==2.5.0\n'''\n\nprint(\"requirements.txt:\")\nprint(requirements)"),
    
    md("## Building and Running\n\n```bash\n# Build the image\ndocker build -t ml-api:v1 .\n\n# Run the container\ndocker run -d -p 8000:8000 --name ml-api ml-api:v1\n\n# Check logs\ndocker logs ml-api\n\n# Test the API\ncurl http://localhost:8000/health\n```"),
    
    md("## Multi-Stage Build (Optimized)"),
    
    code("optimized_dockerfile = '''# Stage 1: Build dependencies\nFROM python:3.11-slim AS builder\n\nWORKDIR /app\n\n# Install build dependencies\nRUN apt-get update && apt-get install -y --no-install-recommends \\\n    gcc \\\n    g++ \\\n    && rm -rf /var/lib/apt/lists/*\n\n# Install Python packages\nCOPY requirements.txt .\nRUN pip install --user --no-cache-dir -r requirements.txt\n\n# Stage 2: Runtime\nFROM python:3.11-slim\n\nWORKDIR /app\n\n# Copy only necessary files from builder\nCOPY --from=builder /root/.local /root/.local\n\n# Copy application code\nCOPY main.py .\nCOPY models/ models/\n\n# Update PATH\nENV PATH=/root/.local/bin:$PATH\n\nEXPOSE 8000\n\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n'''\n\nprint(\"Optimized Multi-Stage Dockerfile:\")\nprint(optimized_dockerfile)\nprint(\"\\nBenefits:\")\nprint(\"- Smaller image size (no build tools in final image)\")\nprint(\"- Faster deployment\")\nprint(\"- Better security (fewer packages)\")"),
    
    md("## Docker Compose for Multi-Container Apps"),
    
    code("docker_compose = '''version: '3.8'\n\nservices:\n  # ML API Service\n  api:\n    build: .\n    ports:\n      - \"8000:8000\"\n    environment:\n      - MODEL_PATH=/app/models\n      - REDIS_HOST=redis\n    depends_on:\n      - redis\n    volumes:\n      - ./models:/app/models\n  \n  # Redis for caching\n  redis:\n    image: redis:7-alpine\n    ports:\n      - \"6379:6379\"\n  \n  # Monitoring\n  prometheus:\n    image: prom/prometheus:latest\n    ports:\n      - \"9090:9090\"\n    volumes:\n      - ./prometheus.yml:/etc/prometheus/prometheus.yml\n'''\n\nprint(\"docker-compose.yml:\")\nprint(docker_compose)\nprint(\"\\nUsage:\")\nprint(\"  docker-compose up -d     # Start all services\")\nprint(\"  docker-compose down       # Stop all services\")\nprint(\"  docker-compose logs -f   # View logs\")"),
    
    md("## API with Redis Caching"),
    
    code("from fastapi import FastAPI\nimport redis\nimport json\nimport hashlib\n\napp = FastAPI()\n\n# Connect to Redis\ntry:\n    cache = redis.Redis(host='redis', port=6379, decode_responses=True)\n    cache.ping()\n    print(\"✓ Connected to Redis\")\nexcept:\n    cache = None\n    print(\"⚠️  Redis not available, running without cache\")\n\ndef get_cache_key(data):\n    \"\"\"Generate cache key from input\"\"\"\n    return hashlib.md5(json.dumps(data, sort_keys=True).encode()).hexdigest()\n\n@app.post(\"/predict\")\nasync def predict(features: dict):\n    # Check cache\n    if cache:\n        cache_key = get_cache_key(features)\n        cached_result = cache.get(cache_key)\n        \n        if cached_result:\n            print(\"✓ Cache hit\")\n            return {\"prediction\": json.loads(cached_result), \"cached\": True}\n    \n    # Perform prediction (mock)\n    result = {\"class\": 0, \"confidence\": 0.95}\n    \n    # Cache result (1 hour TTL)\n    if cache:\n        cache.setex(cache_key, 3600, json.dumps(result))\n        print(\"✓ Result cached\")\n    \n    return {\"prediction\": result, \"cached\": False}\n\nprint(\"API with caching ready\")"),
    
    md("## Best Practices\n\n### Image Optimization\n\n1. **Use specific base images**\n   ```dockerfile\n   FROM python:3.11-slim  # Not 'latest'\n   ```\n\n2. **Minimize layers**\n   ```dockerfile\n   # Bad (multiple layers)\n   RUN pip install pandas\n   RUN pip install numpy\n   \n   # Good (single layer)\n   RUN pip install pandas numpy\n   ```\n\n3. **Use .dockerignore**\n   ```\n   __pycache__\n   *.pyc\n   .git\n   .env\n   tests/\n   *.md\n   ```\n\n4. **Order matters (cache)**\n   ```dockerfile\n   # Copy requirements first (changes less often)\n   COPY requirements.txt .\n   RUN pip install -r requirements.txt\n   \n   # Copy code last (changes often)\n   COPY . .\n   ```"),
    
    md("## Health Checks"),
    
    code("healthcheck_dockerfile = '''FROM python:3.11-slim\n\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\n\n# Add health check\nHEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \\\n  CMD curl -f http://localhost:8000/health || exit 1\n\nEXPOSE 8000\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n'''\n\nprint(\"Dockerfile with health check:\")\nprint(healthcheck_dockerfile)"),
    
    md("## Deployment Workflow\n\n### 1. Build\n```bash\ndocker build -t myapp:v1.0 .\n```\n\n### 2. Test Locally\n```bash\ndocker run -p 8000:8000 myapp:v1.0\ncurl http://localhost:8000/health\n```\n\n### 3. Tag for Registry\n```bash\ndocker tag myapp:v1.0 myregistry.com/myapp:v1.0\n```\n\n### 4. Push to Registry\n```bash\ndocker push myregistry.com/myapp:v1.0\n```\n\n### 5. Deploy\n```bash\n# Pull and run on production server\ndocker pull myregistry.com/myapp:v1.0\ndocker run -d -p 8000:8000 myregistry.com/myapp:v1.0\n```"),
    
    md("## Key Takeaways\n\n✅ Docker ensures consistent environments\n✅ Multi-stage builds reduce image size\n✅ Docker Compose manages multi-container apps\n✅ Caching speeds up predictions\n✅ Health checks enable monitoring\n✅ Follow best practices for production")
]

# Notebook 05: Monitoring
notebook_05 = [
    md("# Monitoring ML Models in Production\n\n## 🎯 Learning Objectives\n\n- Implement logging and metrics\n- Monitor model performance\n- Detect data drift\n- Set up alerts\n- Build monitoring dashboards\n\n## Why Monitor?\n\n**What can go wrong:**\n- Model degradation over time\n- Data distribution changes (drift)\n- Infrastructure issues\n- Latency problems\n- Silent failures\n\n**Monitoring helps:**\n- Detect issues early\n- Maintain model quality\n- Track business metrics\n- Optimize resources"),
    
    md("## Types of Monitoring\n\n### 1. System Monitoring\n- **Latency**: Response time (p50, p95, p99)\n- **Throughput**: Requests per second\n- **Errors**: Error rate, types\n- **Resources**: CPU, memory, disk\n\n### 2. Model Monitoring\n- **Prediction distribution**: Are predictions changing?\n- **Confidence scores**: Is model uncertain?\n- **Feature distribution**: Input drift\n- **Performance metrics**: Accuracy, precision, recall\n\n### 3. Business Monitoring\n- **User engagement**: Click-through rate\n- **Conversions**: Sales, sign-ups\n- **Revenue impact**: Direct business value"),
    
    code("# Install dependencies\n# !pip install prometheus-client psutil"),
    
    md("## Basic Logging"),
    
    code("import logging\nfrom datetime import datetime\nimport json\n\n# Configure logging\nlogging.basicConfig(\n    level=logging.INFO,\n    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',\n    handlers=[\n        logging.FileHandler('ml_api.log'),\n        logging.StreamHandler()\n    ]\n)\n\nlogger = logging.getLogger(__name__)\n\ndef log_prediction(model_version, input_data, prediction, latency_ms):\n    \"\"\"Log prediction details\"\"\"\n    log_entry = {\n        \"timestamp\": datetime.now().isoformat(),\n        \"model_version\": model_version,\n        \"input\": input_data,\n        \"prediction\": prediction,\n        \"latency_ms\": latency_ms\n    }\n    logger.info(f\"Prediction: {json.dumps(log_entry)}\")\n\n# Example\nlog_prediction(\n    model_version=\"v1.0\",\n    input_data={\"features\": [1, 2, 3, 4]},\n    prediction={\"class\": 0, \"confidence\": 0.95},\n    latency_ms=12.5\n)\nprint(\"✓ Logging configured\")"),
    
    md("## Metrics with Prometheus"),
    
    code("from prometheus_client import Counter, Histogram, Gauge, generate_latest\nfrom fastapi import FastAPI, Response\nimport time\n\napp = FastAPI()\n\n# Define metrics\nPREDICTION_COUNT = Counter(\n    'predictions_total',\n    'Total number of predictions',\n    ['model_version', 'status']\n)\n\nPREDICTION_LATENCY = Histogram(\n    'prediction_latency_seconds',\n    'Prediction latency in seconds',\n    ['model_version']\n)\n\nMODEL_CONFIDENCE = Histogram(\n    'model_confidence',\n    'Model confidence scores',\n    ['model_version'],\n    buckets=[0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99, 1.0]\n)\n\nACTIVE_REQUESTS = Gauge(\n    'active_requests',\n    'Number of active requests'\n)\n\n@app.post(\"/predict\")\nasync def predict(features: list):\n    ACTIVE_REQUESTS.inc()\n    \n    start_time = time.time()\n    model_version = \"v1.0\"\n    \n    try:\n        # Mock prediction\n        prediction = {\"class\": 0, \"confidence\": 0.95}\n        \n        # Record metrics\n        latency = time.time() - start_time\n        PREDICTION_LATENCY.labels(model_version=model_version).observe(latency)\n        MODEL_CONFIDENCE.labels(model_version=model_version).observe(prediction[\"confidence\"])\n        PREDICTION_COUNT.labels(model_version=model_version, status=\"success\").inc()\n        \n        return prediction\n    \n    except Exception as e:\n        PREDICTION_COUNT.labels(model_version=model_version, status=\"error\").inc()\n        raise\n    \n    finally:\n        ACTIVE_REQUESTS.dec()\n\n@app.get(\"/metrics\")\nasync def metrics():\n    \"\"\"Prometheus metrics endpoint\"\"\"\n    return Response(content=generate_latest(), media_type=\"text/plain\")\n\nprint(\"✓ Metrics configured\")"),
    
    md("## Data Drift Detection"),
    
    code("import numpy as np\nfrom scipy import stats\nfrom collections import deque\n\nclass DriftDetector:\n    \"\"\"Simple drift detector using statistical tests\"\"\"\n    \n    def __init__(self, reference_data, window_size=1000):\n        self.reference_data = np.array(reference_data)\n        self.current_window = deque(maxlen=window_size)\n        self.drift_threshold = 0.05  # p-value threshold\n    \n    def add_sample(self, sample):\n        \"\"\"Add new sample to current window\"\"\"\n        self.current_window.append(sample)\n    \n    def detect_drift(self):\n        \"\"\"Detect drift using Kolmogorov-Smirnov test\"\"\"\n        if len(self.current_window) < 30:  # Need minimum samples\n            return False, 1.0\n        \n        current_data = np.array(list(self.current_window))\n        \n        # KS test for each feature\n        p_values = []\n        for i in range(self.reference_data.shape[1]):\n            statistic, p_value = stats.ks_2samp(\n                self.reference_data[:, i],\n                current_data[:, i]\n            )\n            p_values.append(p_value)\n        \n        # Drift if any feature has low p-value\n        min_p_value = min(p_values)\n        drift_detected = min_p_value < self.drift_threshold\n        \n        return drift_detected, min_p_value\n    \n    def get_drift_report(self):\n        \"\"\"Get detailed drift report\"\"\"\n        drift_detected, p_value = self.detect_drift()\n        \n        return {\n            \"drift_detected\": drift_detected,\n            \"p_value\": p_value,\n            \"threshold\": self.drift_threshold,\n            \"window_size\": len(self.current_window)\n        }\n\n# Example usage\nreference_data = np.random.randn(1000, 4)  # Training data\ndetector = DriftDetector(reference_data)\n\n# Add new samples\nfor _ in range(100):\n    new_sample = np.random.randn(4)\n    detector.add_sample(new_sample)\n\n# Check for drift\nreport = detector.get_drift_report()\nprint(\"Drift Report:\", report)"),
    
    md("## Alert System"),
    
    code("from dataclasses import dataclass\nfrom typing import Callable, List\nfrom enum import Enum\n\nclass AlertSeverity(Enum):\n    INFO = \"info\"\n    WARNING = \"warning\"\n    CRITICAL = \"critical\"\n\n@dataclass\nclass Alert:\n    severity: AlertSeverity\n    message: str\n    metric_name: str\n    metric_value: float\n    threshold: float\n\nclass AlertManager:\n    \"\"\"Manage alerts and notifications\"\"\"\n    \n    def __init__(self):\n        self.handlers: List[Callable] = []\n        self.alerts: List[Alert] = []\n    \n    def add_handler(self, handler: Callable):\n        \"\"\"Add alert handler (e.g., email, Slack)\"\"\"\n        self.handlers.append(handler)\n    \n    def check_metric(self, metric_name, value, threshold, severity=AlertSeverity.WARNING):\n        \"\"\"Check if metric exceeds threshold\"\"\"\n        if value > threshold:\n            alert = Alert(\n                severity=severity,\n                message=f\"{metric_name} exceeded threshold: {value:.2f} > {threshold:.2f}\",\n                metric_name=metric_name,\n                metric_value=value,\n                threshold=threshold\n            )\n            self.trigger_alert(alert)\n    \n    def trigger_alert(self, alert: Alert):\n        \"\"\"Trigger alert to all handlers\"\"\"\n        self.alerts.append(alert)\n        \n        for handler in self.handlers:\n            handler(alert)\n    \n    def get_recent_alerts(self, n=10):\n        \"\"\"Get recent alerts\"\"\"\n        return self.alerts[-n:]\n\n# Example handlers\ndef console_handler(alert: Alert):\n    icon = {\"info\": \"ℹ️\", \"warning\": \"⚠️\", \"critical\": \"🚨\"}[alert.severity.value]\n    print(f\"{icon} [{alert.severity.value.upper()}] {alert.message}\")\n\ndef email_handler(alert: Alert):\n    # In practice, send actual email\n    print(f\"📧 Email sent: {alert.message}\")\n\n# Setup alert manager\nalert_mgr = AlertManager()\nalert_mgr.add_handler(console_handler)\nalert_mgr.add_handler(email_handler)\n\n# Check metrics\nalert_mgr.check_metric(\"latency_ms\", 150, 100, AlertSeverity.WARNING)\nalert_mgr.check_metric(\"error_rate\", 0.15, 0.05, AlertSeverity.CRITICAL)\n\nprint(f\"\\nTotal alerts: {len(alert_mgr.get_recent_alerts())}\")"),
    
    md("## Performance Dashboard (Mock)"),
    
    code("import pandas as pd\nimport numpy as np\nfrom datetime import datetime, timedelta\n\nclass PerformanceDashboard:\n    \"\"\"Track and display performance metrics\"\"\"\n    \n    def __init__(self):\n        self.metrics = []\n    \n    def log_request(self, latency_ms, success, model_version):\n        \"\"\"Log request metrics\"\"\"\n        self.metrics.append({\n            \"timestamp\": datetime.now(),\n            \"latency_ms\": latency_ms,\n            \"success\": success,\n            \"model_version\": model_version\n        })\n    \n    def get_summary(self, last_n_minutes=60):\n        \"\"\"Get performance summary\"\"\"\n        if not self.metrics:\n            return \"No data available\"\n        \n        df = pd.DataFrame(self.metrics)\n        cutoff = datetime.now() - timedelta(minutes=last_n_minutes)\n        recent_df = df[df['timestamp'] > cutoff]\n        \n        if recent_df.empty:\n            return \"No recent data\"\n        \n        summary = {\n            \"total_requests\": len(recent_df),\n            \"success_rate\": recent_df['success'].mean() * 100,\n            \"avg_latency_ms\": recent_df['latency_ms'].mean(),\n            \"p95_latency_ms\": recent_df['latency_ms'].quantile(0.95),\n            \"p99_latency_ms\": recent_df['latency_ms'].quantile(0.99),\n            \"max_latency_ms\": recent_df['latency_ms'].max()\n        }\n        \n        return summary\n    \n    def display_summary(self):\n        \"\"\"Display formatted summary\"\"\"\n        summary = self.get_summary()\n        if isinstance(summary, str):\n            print(summary)\n            return\n        \n        print(\"\\n=== Performance Summary (Last 60 min) ===\")\n        print(f\"Total Requests: {summary['total_requests']}\")\n        print(f\"Success Rate:   {summary['success_rate']:.2f}%\")\n        print(f\"Avg Latency:    {summary['avg_latency_ms']:.2f}ms\")\n        print(f\"P95 Latency:    {summary['p95_latency_ms']:.2f}ms\")\n        print(f\"P99 Latency:    {summary['p99_latency_ms']:.2f}ms\")\n        print(f\"Max Latency:    {summary['max_latency_ms']:.2f}ms\")\n        print(\"=\"  * 40)\n\n# Example usage\ndashboard = PerformanceDashboard()\n\n# Simulate requests\nfor _ in range(1000):\n    latency = np.random.gamma(2, 15)  # Realistic latency distribution\n    success = np.random.random() > 0.02  # 98% success rate\n    dashboard.log_request(latency, success, \"v1.0\")\n\ndashboard.display_summary()"),
    
    md("## Best Practices\n\n1. **Monitor Everything**\n   - System metrics (CPU, memory, latency)\n   - Model metrics (confidence, predictions)\n   - Business metrics (conversions, revenue)\n\n2. **Set Meaningful Alerts**\n   - Not too sensitive (alert fatigue)\n   - Not too relaxed (miss issues)\n   - Actionable thresholds\n\n3. **Track Trends**\n   - Don't just monitor current values\n   - Look for degradation over time\n   - Use moving averages\n\n4. **Automate Responses**\n   - Auto-scaling on high load\n   - Automatic rollback on errors\n   - Self-healing systems\n\n5. **Regular Reviews**\n   - Weekly performance reviews\n   - Monthly model evaluations\n   - Quarterly business impact analysis\n\n## Key Takeaways\n\n✅ Monitor system, model, and business metrics\n✅ Detect data drift proactively\n✅ Set up meaningful alerts\n✅ Build dashboards for visibility\n✅ Automate responses when possible")
]

# Notebook 06: CI/CD
notebook_06 = [
    md("# CI/CD for Machine Learning\n\n## 🎯 Learning Objectives\n\n- Understand CI/CD for ML\n- Automate model training\n- Implement automated testing\n- Deploy models automatically\n- Version control everything\n\n## What is CI/CD for ML?\n\n**CI (Continuous Integration):**\n- Automated testing of code changes\n- Model validation on every commit\n- Data validation\n- Integration tests\n\n**CD (Continuous Deployment):**\n- Automated model deployment\n- Gradual rollout (canary, A/B)\n- Automated monitoring\n- Rollback on failure"),
    
    md("## ML Pipeline Stages\n\n```\nCode Change → Test → Train → Evaluate → Deploy → Monitor\n     ↓         ↓      ↓        ↓         ↓         ↓\n  Linting   Unit   Model   Metrics  Registry  Alerts\n  Type      Data   Valid   Compare  Version   Dashboard\n  Check     Valid  Schema  A/B Test Package\n```"),
    
    md("## Testing ML Code"),
    
    code("# Example test file: test_model.py\nimport pytest\nimport numpy as np\nfrom sklearn.datasets import load_iris\nfrom sklearn.ensemble import RandomForestClassifier\n\nclass TestModel:\n    \"\"\"Test suite for ML model\"\"\"\n    \n    @pytest.fixture\n    def sample_data(self):\n        \"\"\"Provide sample data for tests\"\"\"\n        iris = load_iris()\n        return iris.data[:10], iris.target[:10]\n    \n    def test_model_trains(self, sample_data):\n        \"\"\"Test that model can be trained\"\"\"\n        X, y = sample_data\n        model = RandomForestClassifier(n_estimators=10, random_state=42)\n        model.fit(X, y)\n        \n        assert hasattr(model, 'estimators_')\n        print(\"✓ Model trains successfully\")\n    \n    def test_model_predicts(self, sample_data):\n        \"\"\"Test that model makes predictions\"\"\"\n        X, y = sample_data\n        model = RandomForestClassifier(n_estimators=10, random_state=42)\n        model.fit(X, y)\n        \n        predictions = model.predict(X)\n        \n        assert len(predictions) == len(X)\n        assert all(p in [0, 1, 2] for p in predictions)\n        print(\"✓ Model predicts successfully\")\n    \n    def test_model_accuracy(self, sample_data):\n        \"\"\"Test minimum accuracy threshold\"\"\"\n        X, y = sample_data\n        model = RandomForestClassifier(n_estimators=10, random_state=42)\n        model.fit(X, y)\n        \n        predictions = model.predict(X)\n        accuracy = (predictions == y).mean()\n        \n        assert accuracy >= 0.7, f\"Accuracy {accuracy} below threshold\"\n        print(f\"✓ Model accuracy: {accuracy:.2%}\")\n\n# Run tests (would use pytest in practice)\ntests = TestModel()\ndata = tests.sample_data()\ntests.test_model_trains(data)\ntests.test_model_predicts(data)\ntests.test_model_accuracy(data)"),
    
    md("## Data Validation"),
    
    code("import numpy as np\nfrom typing import Dict, Any\n\nclass DataValidator:\n    \"\"\"Validate input data quality\"\"\"\n    \n    def __init__(self, schema: Dict[str, Any]):\n        self.schema = schema\n    \n    def validate_schema(self, data: np.ndarray) -> bool:\n        \"\"\"Check data matches expected schema\"\"\"\n        expected_features = self.schema['n_features']\n        \n        if data.ndim != 2:\n            raise ValueError(f\"Expected 2D array, got {data.ndim}D\")\n        \n        if data.shape[1] != expected_features:\n            raise ValueError(\n                f\"Expected {expected_features} features, got {data.shape[1]}\"\n            )\n        \n        return True\n    \n    def validate_ranges(self, data: np.ndarray) -> bool:\n        \"\"\"Check feature values are in expected ranges\"\"\"\n        for i, (min_val, max_val) in enumerate(self.schema['feature_ranges']):\n            feature_data = data[:, i]\n            \n            if feature_data.min() < min_val or feature_data.max() > max_val:\n                raise ValueError(\n                    f\"Feature {i} out of range: \"\n                    f\"[{feature_data.min():.2f}, {feature_data.max():.2f}] \"\n                    f\"not in [{min_val}, {max_val}]\"\n                )\n        \n        return True\n    \n    def validate_missing(self, data: np.ndarray) -> bool:\n        \"\"\"Check for missing values\"\"\"\n        if np.isnan(data).any():\n            raise ValueError(\"Data contains NaN values\")\n        \n        if np.isinf(data).any():\n            raise ValueError(\"Data contains infinite values\")\n        \n        return True\n    \n    def validate_all(self, data: np.ndarray) -> Dict[str, bool]:\n        \"\"\"Run all validations\"\"\"\n        results = {\n            'schema': self.validate_schema(data),\n            'ranges': self.validate_ranges(data),\n            'missing': self.validate_missing(data)\n        }\n        return results\n\n# Example usage\nschema = {\n    'n_features': 4,\n    'feature_ranges': [(0, 10), (0, 10), (0, 10), (0, 10)]\n}\n\nvalidator = DataValidator(schema)\n\n# Valid data\nvalid_data = np.random.rand(10, 4) * 10\nresults = validator.validate_all(valid_data)\nprint(\"Validation results:\", results)\nprint(\"✓ All validations passed\")"),
    
    md("## GitHub Actions Workflow\n\nExample `.github/workflows/ml-pipeline.yml`:"),
    
    code("github_workflow = '''\nname: ML Pipeline\n\non:\n  push:\n    branches: [ main ]\n  pull_request:\n    branches: [ main ]\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    \n    steps:\n    - uses: actions/checkout@v3\n    \n    - name: Set up Python\n      uses: actions/setup-python@v4\n      with:\n        python-version: '3.11'\n    \n    - name: Install dependencies\n      run: |\n        pip install -r requirements.txt\n        pip install pytest pytest-cov\n    \n    - name: Run tests\n      run: |\n        pytest tests/ --cov=. --cov-report=xml\n    \n    - name: Validate data schema\n      run: |\n        python scripts/validate_data.py\n  \n  train:\n    needs: test\n    runs-on: ubuntu-latest\n    \n    steps:\n    - uses: actions/checkout@v3\n    \n    - name: Set up Python\n      uses: actions/setup-python@v4\n      with:\n        python-version: '3.11'\n    \n    - name: Install dependencies\n      run: pip install -r requirements.txt\n    \n    - name: Train model\n      run: python scripts/train_model.py\n    \n    - name: Evaluate model\n      run: python scripts/evaluate_model.py\n    \n    - name: Upload model artifact\n      uses: actions/upload-artifact@v3\n      with:\n        name: model\n        path: models/\n  \n  deploy:\n    needs: train\n    runs-on: ubuntu-latest\n    if: github.ref == 'refs/heads/main'\n    \n    steps:\n    - uses: actions/checkout@v3\n    \n    - name: Download model\n      uses: actions/download-artifact@v3\n      with:\n        name: model\n        path: models/\n    \n    - name: Build Docker image\n      run: docker build -t ml-api:${{ github.sha }} .\n    \n    - name: Push to registry\n      run: |\n        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin\n        docker push ml-api:${{ github.sha }}\n'''\n\nprint(\"GitHub Actions Workflow:\")\nprint(github_workflow)"),
    
    md("## Model Training Script"),
    
    code("# scripts/train_model.py (example)\nimport joblib\nimport json\nfrom datetime import datetime\nfrom sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score, f1_score\n\ndef train_model():\n    \"\"\"Train and save model\"\"\"\n    print(\"Loading data...\")\n    iris = load_iris()\n    X_train, X_test, y_train, y_test = train_test_split(\n        iris.data, iris.target, test_size=0.2, random_state=42\n    )\n    \n    print(\"Training model...\")\n    model = RandomForestClassifier(n_estimators=100, random_state=42)\n    model.fit(X_train, y_train)\n    \n    print(\"Evaluating model...\")\n    y_pred = model.predict(X_test)\n    accuracy = accuracy_score(y_test, y_pred)\n    f1 = f1_score(y_test, y_pred, average='weighted')\n    \n    print(f\"Accuracy: {accuracy:.4f}\")\n    print(f\"F1 Score: {f1:.4f}\")\n    \n    # Save model\n    model_path = 'models/model.pkl'\n    joblib.dump(model, model_path)\n    print(f\"Model saved to {model_path}\")\n    \n    # Save metrics\n    metrics = {\n        'accuracy': accuracy,\n        'f1_score': f1,\n        'timestamp': datetime.now().isoformat(),\n        'n_samples': len(X_train)\n    }\n    \n    with open('models/metrics.json', 'w') as f:\n        json.dump(metrics, f, indent=2)\n    print(\"Metrics saved\")\n    \n    # Minimum quality gate\n    MIN_ACCURACY = 0.85\n    if accuracy < MIN_ACCURACY:\n        raise ValueError(\n            f\"Model accuracy {accuracy:.4f} below threshold {MIN_ACCURACY}\"\n        )\n    \n    print(\"✓ Training complete, quality gates passed\")\n    return model, metrics\n\n# Run training\nmodel, metrics = train_model()\nprint(\"\\nFinal Metrics:\", json.dumps(metrics, indent=2))"),
    
    md("## Automated Deployment Strategy"),
    
    code("deployment_script = '''\n#!/bin/bash\n# scripts/deploy.sh\n\nset -e  # Exit on error\n\nMODEL_VERSION=$1\nENVIRONMENT=$2\n\nif [ -z \"$MODEL_VERSION\" ] || [ -z \"$ENVIRONMENT\" ]; then\n    echo \"Usage: deploy.sh <version> <environment>\"\n    exit 1\nfi\n\necho \"Deploying model $MODEL_VERSION to $ENVIRONMENT\"\n\n# 1. Run smoke tests\necho \"Running smoke tests...\"\npytest tests/smoke/ --model-version=$MODEL_VERSION\n\n# 2. Deploy with canary strategy\necho \"Starting canary deployment (10% traffic)...\"\nkubectl set image deployment/ml-api \\\n    ml-api=myregistry/ml-api:$MODEL_VERSION \\\n    --canary-weight=10\n\n# 3. Monitor for 5 minutes\necho \"Monitoring canary for 5 minutes...\"\nsleep 300\n\n# 4. Check metrics\nERROR_RATE=$(curl -s prometheus:9090/api/v1/query?query=error_rate | jq '.data.result[0].value[1]')\n\nif (( $(echo \"$ERROR_RATE > 0.01\" | bc -l) )); then\n    echo \"Error rate too high, rolling back...\"\n    kubectl rollout undo deployment/ml-api\n    exit 1\nfi\n\n# 5. Promote to 100%\necho \"Promoting to 100% traffic...\"\nkubectl set image deployment/ml-api \\\n    ml-api=myregistry/ml-api:$MODEL_VERSION \\\n    --canary-weight=100\n\necho \"✓ Deployment complete\"\n'''\n\nprint(\"Deployment Script:\")\nprint(deployment_script)"),
    
    md("## Best Practices\n\n1. **Version Everything**\n   - Code (Git)\n   - Data (DVC, S3 versioning)\n   - Models (MLflow, model registry)\n   - Dependencies (requirements.txt with versions)\n\n2. **Automated Testing**\n   - Unit tests for code\n   - Data validation tests\n   - Model performance tests\n   - Integration tests\n\n3. **Quality Gates**\n   - Minimum accuracy threshold\n   - Maximum latency\n   - Code coverage\n   - Linting/formatting\n\n4. **Gradual Rollout**\n   - Start with canary (5-10%)\n   - Monitor key metrics\n   - Increase gradually\n   - Auto-rollback on issues\n\n5. **Documentation**\n   - README with setup instructions\n   - API documentation\n   - Model cards\n   - Runbooks for incidents\n\n## Key Takeaways\n\n✅ Automate testing and deployment\n✅ Validate data and models automatically\n✅ Use quality gates to prevent bad deployments\n✅ Implement gradual rollout strategies\n✅ Version and document everything")
]

# Notebook 07: Cloud Deployment
notebook_07 = [
    md("# Cloud Deployment for ML Models\n\n## 🎯 Learning Objectives\n\n- Deploy models to cloud platforms\n- Use managed ML services\n- Implement auto-scaling\n- Optimize costs\n- Set up cloud monitoring\n\n## Cloud Platform Options\n\n### AWS\n- **SageMaker**: End-to-end ML platform\n- **Lambda**: Serverless inference\n- **ECS/EKS**: Container orchestration\n- **S3**: Model storage\n\n### Azure\n- **Azure ML**: Managed ML platform\n- **Azure Functions**: Serverless\n- **AKS**: Kubernetes service\n- **Blob Storage**: Model storage\n\n### GCP\n- **Vertex AI**: Unified ML platform\n- **Cloud Run**: Serverless containers\n- **GKE**: Kubernetes Engine\n- **Cloud Storage**: Model storage"),
    
    md("## Deployment Options Comparison\n\n| Option | Best For | Pros | Cons |\n|--------|----------|------|------|\n| **Serverless** | Low traffic, variable load | No server management, auto-scale, pay per use | Cold starts, limited resources |\n| **Containers** | Medium traffic, consistent load | Flexible, portable, good control | Requires orchestration |\n| **Kubernetes** | High traffic, complex apps | Powerful, scalable, resilient | Complex setup |\n| **Managed ML** | Quick deployment | Easy setup, managed infrastructure | Less control, vendor lock-in |"),
    
    md("## AWS Lambda Deployment"),
    
    code("# Example: AWS Lambda handler for ML model\nimport json\nimport boto3\nimport numpy as np\nimport joblib\nfrom io import BytesIO\n\n# Initialize S3 client\ns3 = boto3.client('s3')\n\n# Load model from S3 (cached globally)\nMODEL = None\nMODEL_BUCKET = 'my-ml-models'\nMODEL_KEY = 'iris-classifier/model.pkl'\n\ndef load_model():\n    \"\"\"Load model from S3\"\"\"\n    global MODEL\n    if MODEL is None:\n        print(\"Loading model from S3...\")\n        obj = s3.get_object(Bucket=MODEL_BUCKET, Key=MODEL_KEY)\n        MODEL = joblib.load(BytesIO(obj['Body'].read()))\n        print(\"Model loaded\")\n    return MODEL\n\ndef lambda_handler(event, context):\n    \"\"\"AWS Lambda handler function\"\"\"\n    try:\n        # Parse input\n        body = json.loads(event['body'])\n        features = np.array(body['features']).reshape(1, -1)\n        \n        # Load model\n        model = load_model()\n        \n        # Predict\n        prediction = model.predict(features)[0]\n        probabilities = model.predict_proba(features)[0]\n        \n        # Return response\n        return {\n            'statusCode': 200,\n            'headers': {\n                'Content-Type': 'application/json',\n                'Access-Control-Allow-Origin': '*'\n            },\n            'body': json.dumps({\n                'prediction': int(prediction),\n                'probabilities': probabilities.tolist(),\n                'model_version': '1.0'\n            })\n        }\n    \n    except Exception as e:\n        return {\n            'statusCode': 500,\n            'body': json.dumps({'error': str(e)})\n        }\n\nprint(\"Lambda handler defined\")\nprint(\"\\nDeploy with:\")\nprint(\"  1. Package: zip -r function.zip .\")\nprint(\"  2. Upload: aws lambda create-function ...\")\nprint(\"  3. Create API Gateway endpoint\")"),
    
    md("## Kubernetes Deployment"),
    
    code("k8s_deployment = '''\n# deployment.yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ml-api\n  labels:\n    app: ml-api\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: ml-api\n  template:\n    metadata:\n      labels:\n        app: ml-api\n    spec:\n      containers:\n      - name: ml-api\n        image: myregistry/ml-api:v1.0\n        ports:\n        - containerPort: 8000\n        resources:\n          requests:\n            memory: \"512Mi\"\n            cpu: \"500m\"\n          limits:\n            memory: \"1Gi\"\n            cpu: \"1000m\"\n        env:\n        - name: MODEL_PATH\n          value: \"/models/model.pkl\"\n        livenessProbe:\n          httpGet:\n            path: /health\n            port: 8000\n          initialDelaySeconds: 30\n          periodSeconds: 10\n        readinessProbe:\n          httpGet:\n            path: /health\n            port: 8000\n          initialDelaySeconds: 5\n          periodSeconds: 5\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: ml-api-service\nspec:\n  selector:\n    app: ml-api\n  ports:\n  - protocol: TCP\n    port: 80\n    targetPort: 8000\n  type: LoadBalancer\n---\napiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: ml-api-hpa\nspec:\n  scaleTargetRef:\n    apiVersion: apps/v1\n    kind: Deployment\n    name: ml-api\n  minReplicas: 2\n  maxReplicas: 10\n  metrics:\n  - type: Resource\n    resource:\n      name: cpu\n      target:\n        type: Utilization\n        averageUtilization: 70\n  - type: Resource\n    resource:\n      name: memory\n      target:\n        type: Utilization\n        averageUtilization: 80\n'''\n\nprint(\"Kubernetes Deployment Configuration:\")\nprint(k8s_deployment)\nprint(\"\\nDeploy with:\")\nprint(\"  kubectl apply -f deployment.yaml\")"),
    
    md("## Auto-Scaling Configuration"),
    
    code("autoscaling_config = '''\n# Auto-scaling based on custom metrics\n\napiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: ml-api-custom-hpa\nspec:\n  scaleTargetRef:\n    apiVersion: apps/v1\n    kind: Deployment\n    name: ml-api\n  minReplicas: 2\n  maxReplicas: 20\n  metrics:\n  # CPU-based scaling\n  - type: Resource\n    resource:\n      name: cpu\n      target:\n        type: Utilization\n        averageUtilization: 70\n  \n  # Request rate-based scaling\n  - type: Pods\n    pods:\n      metric:\n        name: requests_per_second\n      target:\n        type: AverageValue\n        averageValue: \"100\"\n  \n  # Queue depth scaling\n  - type: External\n    external:\n      metric:\n        name: sqs_queue_depth\n        selector:\n          matchLabels:\n            queue_name: ml_predictions\n      target:\n        type: Value\n        value: \"30\"\n  \n  behavior:\n    scaleUp:\n      stabilizationWindowSeconds: 60\n      policies:\n      - type: Percent\n        value: 50\n        periodSeconds: 60\n      - type: Pods\n        value: 2\n        periodSeconds: 60\n    scaleDown:\n      stabilizationWindowSeconds: 300\n      policies:\n      - type: Percent\n        value: 10\n        periodSeconds: 60\n'''\n\nprint(\"Advanced Auto-Scaling Configuration:\")\nprint(autoscaling_config)"),
    
    md("## Cost Optimization Strategies"),
    
    code("import pandas as pd\n\n# Example cost analysis\ncost_analysis = pd.DataFrame([\n    {\n        'Option': 'AWS Lambda',\n        'Fixed Cost/mo': '$0',\n        'Variable Cost': '$0.20 per 1M requests + $0.0000166667 per GB-second',\n        'Best For': 'Low/variable traffic (<100K req/day)',\n        'Break-even': '~50K requests/day'\n    },\n    {\n        'Option': 'ECS Fargate',\n        'Fixed Cost/mo': '~$30-50',\n        'Variable Cost': 'Scales with CPU/memory',\n        'Best For': 'Medium traffic (100K-1M req/day)',\n        'Break-even': '~100K requests/day'\n    },\n    {\n        'Option': 'EC2 + Docker',\n        'Fixed Cost/mo': '~$50-200',\n        'Variable Cost': 'Minimal',\n        'Best For': 'High consistent traffic (>1M req/day)',\n        'Break-even': '~500K requests/day'\n    },\n    {\n        'Option': 'Spot Instances',\n        'Fixed Cost/mo': '$0',\n        'Variable Cost': '60-90% less than EC2',\n        'Best For': 'Batch predictions, non-critical',\n        'Break-even': 'Always cheaper (if workload fits)'\n    }\n])\n\nprint(\"Cost Comparison:\")\nprint(cost_analysis.to_string(index=False))\n\nprint(\"\\n=== Cost Optimization Tips ===\")\ntips = [\n    \"1. Use spot instances for batch processing\",\n    \"2. Right-size instances (monitor actual usage)\",\n    \"3. Enable auto-scaling to avoid over-provisioning\",\n    \"4. Use reserved instances for predictable workloads\",\n    \"5. Implement caching to reduce compute\",\n    \"6. Compress models to reduce memory needs\",\n    \"7. Use cheaper regions when possible\",\n    \"8. Clean up unused resources regularly\"\n]\n\nfor tip in tips:\n    print(tip)"),
    
    md("## Monitoring in Cloud"),
    
    code("cloudwatch_config = '''\n# AWS CloudWatch alarms (Terraform example)\n\nresource \"aws_cloudwatch_metric_alarm\" \"high_latency\" {\n  alarm_name          = \"ml-api-high-latency\"\n  comparison_operator = \"GreaterThanThreshold\"\n  evaluation_periods  = \"2\"\n  metric_name         = \"Duration\"\n  namespace           = \"AWS/Lambda\"\n  period              = \"60\"\n  statistic           = \"Average\"\n  threshold           = \"1000\"  # 1 second\n  alarm_description   = \"Alert when average latency > 1s\"\n  alarm_actions       = [aws_sns_topic.alerts.arn]\n  \n  dimensions = {\n    FunctionName = aws_lambda_function.ml_api.function_name\n  }\n}\n\nresource \"aws_cloudwatch_metric_alarm\" \"high_error_rate\" {\n  alarm_name          = \"ml-api-high-error-rate\"\n  comparison_operator = \"GreaterThanThreshold\"\n  evaluation_periods  = \"2\"\n  metric_name         = \"Errors\"\n  namespace           = \"AWS/Lambda\"\n  period              = \"60\"\n  statistic           = \"Sum\"\n  threshold           = \"10\"\n  alarm_description   = \"Alert when error count > 10 per minute\"\n  alarm_actions       = [aws_sns_topic.alerts.arn]\n  \n  dimensions = {\n    FunctionName = aws_lambda_function.ml_api.function_name\n  }\n}\n\nresource \"aws_cloudwatch_dashboard\" \"ml_api\" {\n  dashboard_name = \"ml-api-dashboard\"\n  \n  dashboard_body = jsonencode({\n    widgets = [\n      {\n        type = \"metric\"\n        properties = {\n          metrics = [\n            [\"AWS/Lambda\", \"Invocations\", {stat = \"Sum\"}],\n            [\".\", \"Errors\", {stat = \"Sum\"}],\n            [\".\", \"Duration\", {stat = \"Average\"}]\n          ]\n          period = 300\n          stat   = \"Average\"\n          region = \"us-east-1\"\n          title  = \"ML API Metrics\"\n        }\n      }\n    ]\n  })\n}\n'''\n\nprint(\"CloudWatch Monitoring Configuration:\")\nprint(cloudwatch_config)"),
    
    md("## Deployment Checklist\n\n### Pre-Deployment\n- [ ] Code reviewed and tested\n- [ ] Model performance validated\n- [ ] Load testing completed\n- [ ] Security scan passed\n- [ ] Documentation updated\n- [ ] Rollback plan ready\n\n### Deployment\n- [ ] Deploy to staging first\n- [ ] Run smoke tests\n- [ ] Monitor key metrics\n- [ ] Gradual traffic increase\n- [ ] Communicate with stakeholders\n\n### Post-Deployment\n- [ ] Monitor for 24-48 hours\n- [ ] Check error rates\n- [ ] Verify latency\n- [ ] Review costs\n- [ ] Collect user feedback\n- [ ] Document lessons learned"),
    
    md("## Best Practices\n\n1. **Multi-Region Deployment**\n   - Deploy to multiple regions for resilience\n   - Use geo-routing for low latency\n   - Implement cross-region failover\n\n2. **Security**\n   - Use IAM roles (don't embed credentials)\n   - Enable encryption at rest and in transit\n   - Implement API authentication\n   - Regular security audits\n\n3. **Cost Management**\n   - Set up billing alerts\n   - Use cost allocation tags\n   - Right-size resources\n   - Review costs monthly\n\n4. **Reliability**\n   - Implement health checks\n   - Set up auto-recovery\n   - Use multiple availability zones\n   - Regular disaster recovery drills\n\n5. **Observability**\n   - Centralized logging\n   - Distributed tracing\n   - Custom metrics\n   - Real-time dashboards\n\n## Key Takeaways\n\n✅ Choose deployment option based on traffic and budget\n✅ Implement auto-scaling for variable load\n✅ Monitor costs and optimize regularly\n✅ Use managed services when appropriate\n✅ Always have a rollback plan\n✅ Security and observability are critical")
]

print("Creating remaining MLOps notebooks...")
print("=" * 70)

save_notebook("04_docker_ml.ipynb", notebook_04)
print("✓ Notebook 04: Containerizing ML Applications with Docker")

save_notebook("05_monitoring.ipynb", notebook_05)
print("✓ Notebook 05: Monitoring ML Models in Production")

save_notebook("06_ci_cd_pipeline.ipynb", notebook_06)
print("✓ Notebook 06: CI/CD for Machine Learning")

save_notebook("07_cloud_deployment.ipynb", notebook_07)
print("✓ Notebook 07: Cloud Deployment for ML Models")

print("=" * 70)
print("🎉 SUCCESS! All 8 MLOps notebooks created!")
print("\nComplete series:")
print("  00_START_HERE.ipynb")
print("  01_experiment_tracking.ipynb")
print("  02_fastapi_basics.ipynb")
print("  03_model_deployment.ipynb")
print("  04_docker_ml.ipynb")
print("  05_monitoring.ipynb")
print("  06_ci_cd_pipeline.ipynb")
print("  07_cloud_deployment.ipynb")
