export default {
  plot_custom_kernel: "1. Plot Custom Kernel",
  plot_iris_svc: "2. Plot Iris Svc",
  plot_linearsvc_support_vectors: "3. Plot Linearsvc Support Vectors",
  plot_oneclass: "4. Plot Oneclass",
  plot_rbf_parameters: "5. Plot Rbf Parameters",
  plot_separating_hyperplane: "6. Plot Separating Hyperplane",
  plot_separating_hyperplane_unbalanced: "7. Plot Separating Hyperplane Unbalanced",
  plot_svm_anova: "8. Plot Svm Anova",
  plot_svm_kernels: "9. Plot Svm Kernels",
  plot_svm_margin: "10. Plot Svm Margin",
  plot_svm_regression: "11. Plot Svm Regression",
  plot_svm_scale_c: "12. Plot Svm Scale C",
  plot_svm_tie_breaking: "13. Plot Svm Tie Breaking",
  plot_weighted_samples: "14. Plot Weighted Samples",
}
