#!/usr/bin/env python3
"""
Enrich auto-generated shallow markdown cells in Jupyter notebooks with
deep, concept-driven explanations that teach *what* and *why*.

Detects cells generated by the first-pass add_explanations.py script
and replaces them with rich contextual explanations based on the code
that follows.
"""

import json
import re
import sys
from pathlib import Path
from collections import Counter

WORKSPACE = Path("/Users/pavanmudigonda/code/zero-to-ai")

# ────────────────────────────────────────────────────────────────────
# DETECTION: Patterns that identify auto-generated shallow cells
# ────────────────────────────────────────────────────────────────────

AUTO_GEN_PATTERNS = [
    r"^Evaluate the (expression|arithmetic)",
    r"^Display the current value of",
    r"^This code implements the next step in",
    r"^Run this code and examine the printed output",
    r"^Set up the variables needed for the next step",
    r"^Display output to verify the results",
    r"^Execute the next step in this",
    r"^Work with Python (lists|dictionaries|dict)",
    r"^Use a (loop to process|Python comprehension)",
    r"^Use conditional logic",
    r"^Perform string manipul",
    r"^Set up variables and display",
    r"^\*\*Python (Multiplication|Division|Addition|Subtraction|Modulo|Exponentiation):\*\*",
    r"^\*\*Inspect variable",
    r"^\*\*Indexing/Slicing:\*\*",
    r"^### (Mathematical Operations|Visualize the Results|Data Manipulation|Iterative Processing|Data Transformation|File Operations|Error Handling|API Interaction|Tensor Operations|Compute Embeddings|Vector Database|Generate Predictions|Build the Model|Train the Model|Evaluate Model|Load the Data|Preprocess the Data|Configure Loss|Can not start)",
    r"^### Import Required Libraries\n\nLoad the libraries needed",
    r"^### Define the `\w+` Function\n\nDefine a function",
    r"^### Define Helper Functions\n\nDefine these utility",
    r"^### Define `\w+\(\)`\n\nA helper function",
    # Thin headings with no real explanation
    r"^### (Vector Operations|Matrix Operations|Visualizing (Vectors|Matrix|Eigenvectors))\s*$",
]


def is_auto_generated(md_source: str) -> bool:
    """Check if a markdown cell was auto-generated with shallow content."""
    text = md_source.strip()
    for pat in AUTO_GEN_PATTERNS:
        if re.search(pat, text, re.MULTILINE):
            return True
    return False


# ────────────────────────────────────────────────────────────────────
# CONCEPT DATABASE: deep explanations keyed by code patterns
# Each entry: (code_pattern_regex, explanation_text)
# Patterns are checked in order; first match wins per concept
# ────────────────────────────────────────────────────────────────────

CONCEPTS = [
    # ── Linear Algebra ──
    (r"np\.dot\(", "dot_product",
     "**Dot Product (Inner Product):** Measures how much two vectors point in the same "
     "direction. Computed by multiplying corresponding elements and summing:\n\n"
     "$$\\mathbf{a} \\cdot \\mathbf{b} = \\sum_i a_i \\times b_i$$\n\n"
     "- **Positive** result → vectors point roughly the same way\n"
     "- **Zero** → perpendicular (orthogonal)\n"
     "- **Negative** → opposite directions\n\n"
     "In ML, every neuron computes a dot product between its inputs and weights. "
     "Cosine similarity is a normalized dot product."),

    (r"np\.linalg\.norm\(", "norm",
     "**Vector Norm (Magnitude):** Measures the \"length\" of a vector — its distance "
     "from the origin:\n\n"
     "$$\\|\\mathbf{v}\\|_2 = \\sqrt{v_1^2 + v_2^2 + \\cdots + v_n^2}$$\n\n"
     "**Normalizing** (dividing by the norm) creates a unit vector with length 1. "
     "Used in cosine similarity, gradient clipping, and regularization."),

    (r"np\.linalg\.eig\(", "eigen",
     "**Eigenvalues & Eigenvectors:** When matrix $A$ multiplies eigenvector $\\mathbf{v}$, "
     "it only scales it (no rotation):\n\n"
     "$$A\\mathbf{v} = \\lambda\\mathbf{v}$$\n\n"
     "The eigenvalue $\\lambda$ is the scale factor. Eigenvectors reveal the "
     "matrix's \"natural axes.\"\n\n"
     "**ML uses:** PCA (eigenvectors of covariance matrix = principal components), "
     "graph centrality, stability analysis of optimization."),

    (r"np\.linalg\.inv\(", "inverse",
     "**Matrix Inverse:** $A^{-1}$ \"undoes\" matrix $A$: $A \\cdot A^{-1} = I$. "
     "Exists only for square, non-singular matrices (det ≠ 0).\n\n"
     "Used in the Normal Equation for linear regression: "
     "$\\hat{\\beta} = (X^T X)^{-1} X^T y$. "
     "In practice, direct inversion is numerically unstable for large matrices — "
     "use `np.linalg.solve()` or iterative methods instead."),

    (r"np\.linalg\.det\(", "determinant",
     "**Determinant:** A scalar measuring how a matrix scales area/volume.\n"
     "- **det = 0** → singular (no inverse, collapses a dimension)\n"
     "- **det > 0** → preserves orientation\n"
     "- **det < 0** → flips orientation\n\n"
     "Appears in multivariate Gaussian distributions and in checking if a "
     "system of equations has a unique solution."),

    (r"np\.linalg\.svd\(", "svd",
     "**Singular Value Decomposition (SVD):** Factors any matrix as $A = U\\Sigma V^T$ — "
     "two rotations and a scaling. The top-$k$ singular values capture the most important "
     "structure.\n\n"
     "Used in: dimensionality reduction, recommendation systems (matrix factorization), "
     "NLP (Latent Semantic Analysis), and image compression."),

    (r"\bA\.T\b|\.transpose\(|\.T\b", "transpose",
     "**Transpose ($A^T$):** Flips a matrix over its diagonal — rows become columns and "
     "vice versa. If $A$ is (m×n), then $A^T$ is (n×m).\n\n"
     "Properties: $(AB)^T = B^T A^T$, $(A^T)^T = A$. Transpose is fundamental in "
     "the Normal Equation and in computing the gradient of matrix expressions."),

    (r"@ B|matmul|np\.dot\(A", "matmul",
     "**Matrix Multiplication:** Each element of the result is a dot product of a row "
     "of $A$ with a column of $B$:\n\n"
     "$$C_{ij} = \\sum_k A_{ik} B_{kj}$$\n\n"
     "Every neural network layer computes $\\text{output} = W \\cdot x + b$. "
     "The `@` operator is Python shorthand for `np.matmul()`."),

    (r"np\.eye\(", "identity",
     "**Identity Matrix ($I$):** The \"number 1\" of matrix math — multiplying any "
     "matrix by $I$ returns the same matrix: $AI = IA = A$. It's a square matrix "
     "with 1s on the diagonal and 0s elsewhere."),

    # ── Activation Functions ──
    (r"\bsoftmax\b", "softmax",
     "**Softmax:** Converts raw scores (logits) into a probability distribution "
     "that sums to 1:\n\n"
     "$$\\text{softmax}(z_i) = \\frac{e^{z_i}}{\\sum_j e^{z_j}}$$\n\n"
     "Amplifies the largest value and suppresses smaller ones. Used as the final "
     "layer in multi-class classification — the output is the model's confidence per class."),

    (r"\bsigmoid\b", "sigmoid",
     "**Sigmoid:** Squashes any number to the range (0, 1):\n\n"
     "$$\\sigma(x) = \\frac{1}{1 + e^{-x}}$$\n\n"
     "Used for binary classification (output = probability) and as gates in LSTMs. "
     "Downside: gradients vanish for extreme inputs, which is why ReLU replaced it "
     "in hidden layers."),

    (r"\brelu\b|nn\.ReLU", "relu",
     "**ReLU (Rectified Linear Unit):** The most common activation in modern networks:\n\n"
     "$$\\text{ReLU}(x) = \\max(0, x)$$\n\n"
     "Passes positives through, zeroes out negatives. Avoids vanishing gradients "
     "(gradient is 1 for positive inputs), is fast to compute, and creates sparse activations."),

    # ── Loss Functions ──
    (r"CrossEntropy", "cross_entropy",
     "**Cross-Entropy Loss:** The standard for classification. Heavily penalizes "
     "confident wrong predictions:\n\n"
     "$$\\mathcal{L} = -\\sum_c y_c \\log(\\hat{y}_c)$$\n\n"
     "If your model predicts 0.01 for the true class, the loss is very high. "
     "If it predicts 0.99, the loss is near zero."),

    (r"BCELoss|binary_crossentropy", "bce",
     "**Binary Cross-Entropy:** For two-class problems:\n\n"
     "$$\\mathcal{L} = -[y \\log(\\hat{y}) + (1-y)\\log(1-\\hat{y})]$$\n\n"
     "Pair with a sigmoid output layer. When true label is 1, penalize low predictions; "
     "when 0, penalize high predictions."),

    (r"MSELoss|mean_squared_error|mse_loss", "mse",
     "**Mean Squared Error (MSE):** The go-to regression loss:\n\n"
     "$$\\text{MSE} = \\frac{1}{n}\\sum(y_i - \\hat{y}_i)^2$$\n\n"
     "Squaring penalizes large errors disproportionately. Sensitive to outliers — "
     "consider MAE or Huber loss for robust alternatives."),

    # ── Optimizers ──
    (r"\bAdam\(|AdamW\(", "adam",
     "**Adam Optimizer:** Combines momentum (smoothed gradient history) with adaptive "
     "per-parameter learning rates. Default choice for most deep learning tasks.\n\n"
     "**AdamW** adds proper weight decay for better generalization. "
     "Typical learning rates: 1e-3 to 1e-5."),

    (r"\bSGD\(", "sgd",
     "**SGD (Stochastic Gradient Descent):** The foundational optimizer — updates "
     "parameters using the gradient estimated from a mini-batch:\n\n"
     "$$\\theta \\leftarrow \\theta - \\eta \\nabla\\mathcal{L}$$\n\n"
     "SGD with momentum often generalizes better than Adam for vision tasks "
     "but requires more tuning."),

    (r"optimizer\.step\(", "optim_step",
     "**Optimizer Step — the training heartbeat:**\n"
     "1. `optimizer.zero_grad()` — clear old gradients\n"
     "2. `loss.backward()` — compute gradients via backpropagation\n"
     "3. `optimizer.step()` — update weights in the direction that reduces loss\n\n"
     "The step size is controlled by the learning rate."),

    (r"\.backward\(", "backward",
     "**Backpropagation (.backward()):** Triggers automatic differentiation — "
     "PyTorch walks backward through the computation graph, computing the gradient "
     "of the loss with respect to every parameter via the chain rule. "
     "These gradients tell each weight which direction to adjust."),

    # ── Neural Network Layers ──
    (r"nn\.Linear\(", "linear",
     "**Linear Layer (Fully Connected):** Computes $y = xW^T + b$ — a matrix "
     "multiplication plus bias. `nn.Linear(in, out)` transforms a vector of size `in` "
     "to size `out`.\n\n"
     "Without activation functions between linear layers, stacking them is equivalent "
     "to a single linear layer."),

    (r"nn\.Conv[12]d\(", "conv",
     "**Convolutional Layer:** Slides a learned filter (kernel) across the input to "
     "detect local patterns (edges, textures). Exploits spatial locality and shares "
     "parameters — far fewer weights than a fully connected layer.\n\n"
     "- `Conv1d`: sequences (text, time series)\n"
     "- `Conv2d`: images"),

    (r"nn\.LSTM\(|nn\.GRU\(", "rnn",
     "**Recurrent Network (LSTM/GRU):** Processes sequential data by maintaining a "
     "hidden state (\"memory\") across time steps.\n\n"
     "- **LSTM**: Uses forget/input/output gates to control memory\n"
     "- **GRU**: Simplified LSTM with fewer parameters\n\n"
     "While Transformers dominate NLP, LSTMs remain strong for time series."),

    (r"nn\.Module|class.*nn\.Module", "nn_module",
     "**PyTorch Model (nn.Module):** Base class for all neural networks. Define the "
     "architecture in `__init__()` and the forward pass in `forward()`. PyTorch "
     "auto-generates the backward pass for gradient computation."),

    # ── sklearn Models ──
    (r"train_test_split\(", "traintestsplit",
     "**Train/Test Split:** Divides data into training (typically 70-80%) and test "
     "(20-30%) sets. Without this, you can't detect **overfitting** — when a model "
     "memorizes training data but fails on new examples. Use `random_state` for "
     "reproducibility."),

    (r"cross_val_score\(", "crossval",
     "**K-Fold Cross-Validation:** Splits data into $k$ folds, trains on $k-1$, "
     "tests on the remaining one, and rotates through all folds. More robust than "
     "a single train/test split because every data point is tested exactly once."),

    (r"\.fit\(", "fit",
     "**Model Training (.fit()):** The model learns from data by adjusting internal "
     "parameters to minimize prediction errors.\n\n"
     "What `.fit()` does depends on the model:\n"
     "- **Linear models**: finds the best-fit line (minimizes squared error)\n"
     "- **Trees**: learns if/else rules that separate classes\n"
     "- **Scalers/PCA**: computes statistics (mean, variance, components)"),

    (r"\.predict\(", "predict",
     "**Prediction (.predict()):** Applies the learned model to new data. "
     "For classification, returns class labels; for regression, returns continuous values. "
     "Quality depends on training quality and whether new data resembles the training distribution."),

    (r"\.fit_transform\(", "fit_transform",
     "**Fit & Transform:** Learns transformation parameters from data and immediately "
     "applies the transformation in one step.\n\n"
     "**Important:** Only use on training data. For test data, use `.transform()` alone "
     "to apply the *same* transformation learned from training (avoids data leakage)."),

    (r"\.transform\(", "transform_only",
     "**Transform:** Applies a previously learned transformation (from `.fit()`) to new "
     "data. Always use the same transformer object on training and test data to ensure "
     "consistent preprocessing."),

    (r"StandardScaler\(", "stdscaler",
     "**Standard Scaling (Z-score):** Transforms each feature to mean=0, std=1:\n\n"
     "$$z = \\frac{x - \\mu}{\\sigma}$$\n\n"
     "Many algorithms (SVM, KNN, gradient descent, PCA) are sensitive to feature scale. "
     "Tree-based models (Random Forest, XGBoost) are scale-invariant and don't need this."),

    (r"MinMaxScaler\(", "minmax",
     "**Min-Max Scaling:** Rescales features to [0, 1]:\n\n"
     "$$x_{\\text{scaled}} = \\frac{x - x_{\\min}}{x_{\\max} - x_{\\min}}$$\n\n"
     "Use when you need bounded values (neural network inputs, image pixels). "
     "More sensitive to outliers than StandardScaler."),

    (r"PCA\(", "pca",
     "**PCA (Principal Component Analysis):** Finds directions of maximum variance "
     "and projects data onto them. The first component captures the most variance, "
     "the second captures the most of what's left (orthogonal to the first), etc.\n\n"
     "Under the hood, PCA = eigenvectors of the covariance matrix. Uses: "
     "dimensionality reduction, denoising, and visualizing high-dimensional data."),

    (r"LogisticRegression\(", "logreg",
     "**Logistic Regression:** A classification model (despite the name) that uses "
     "the sigmoid function to model class probability:\n\n"
     "$$P(y=1|x) = \\frac{1}{1 + e^{-(w^Tx + b)}}$$\n\n"
     "The decision boundary is a hyperplane. Fast, interpretable, and a strong baseline."),

    (r"LinearRegression\(", "linreg",
     "**Linear Regression:** Fits a line/plane that minimizes squared errors:\n\n"
     "$$\\hat{y} = w_1x_1 + w_2x_2 + \\cdots + b$$\n\n"
     "Each weight $w_i$ measures how much the prediction changes when feature $x_i$ "
     "increases by 1 (holding others constant)."),

    (r"RandomForest", "rf",
     "**Random Forest:** Builds many independent decision trees and averages their "
     "predictions. Each tree sees a random subset of data and features, which "
     "decorrelates the trees and reduces overfitting. Works well out of the box "
     "with minimal tuning."),

    (r"GradientBoosting|XGB|LGBM", "gbm",
     "**Gradient Boosting:** Builds trees sequentially — each corrects the errors of "
     "the previous ones. Each new tree fits the *residual* (what the ensemble got wrong).\n\n"
     "XGBoost and LightGBM are optimized implementations that dominate tabular data competitions."),

    (r"DecisionTree", "tree",
     "**Decision Tree:** Learns if/else rules from data. At each node, picks the "
     "feature and threshold that best separates the target. Highly interpretable but "
     "prone to overfitting — use Random Forest or boosting for better generalization."),

    (r"SVC\(|SVR\(|SVM", "svm",
     "**Support Vector Machine:** Finds the hyperplane that maximizes the margin "
     "(distance to nearest points of each class). The \"kernel trick\" (RBF, polynomial) "
     "handles non-linear boundaries by mapping data to higher dimensions."),

    (r"KMeans\(", "kmeans",
     "**K-Means Clustering:** Unsupervised algorithm that groups data into $k$ clusters "
     "by iteratively assigning points to nearest centroids, then updating centroids. "
     "Choose $k$ with the elbow method or silhouette score."),

    # ── Metrics ──
    (r"accuracy_score\(", "accuracy",
     "**Accuracy:** Fraction of correct predictions. **Caution:** misleading with "
     "imbalanced classes — a model that always predicts the majority class gets high "
     "accuracy while being useless. Use F1-score for imbalanced data."),

    (r"confusion_matrix\(", "confmat",
     "**Confusion Matrix:** A 2×2 table (for binary) showing True Positives, False Positives, "
     "True Negatives, and False Negatives. From it you compute:\n"
     "- **Precision** = TP/(TP+FP) — \"of positive predictions, how many were right?\"\n"
     "- **Recall** = TP/(TP+FN) — \"of actual positives, how many did we find?\""),

    (r"classification_report\(", "classreport",
     "**Classification Report:** Per-class precision, recall, F1, and support:\n"
     "- **Precision**: low → too many false alarms\n"
     "- **Recall**: low → missing real positives\n"
     "- **F1**: harmonic mean balancing both"),

    (r"r2_score\(", "r2",
     "**R² Score:** Fraction of variance explained by the model (1.0 = perfect, "
     "0.0 = no better than guessing the mean, <0 = worse than the mean)."),

    # ── Data ──
    (r"pd\.read_csv\(", "readcsv",
     "**Load CSV Data:** Reads tabular data into a Pandas DataFrame — the primary "
     "structure for data analysis. A DataFrame is like a spreadsheet: rows are "
     "observations, columns are features, each column can have a different type."),

    (r"pd\.DataFrame\(", "dataframe",
     "**Create a DataFrame:** Pandas DataFrames are 2D labeled data structures — the "
     "backbone of data science in Python. They support filtering, grouping, merging, "
     "reshaping, and aggregation."),

    (r"\.groupby\(", "groupby",
     "**GroupBy (Split-Apply-Combine):** Splits data by a key, applies a function to "
     "each group (mean, sum, count), and combines the results. "
     "Example: `df.groupby('city')['price'].mean()` → average price per city."),

    (r"\.merge\(", "merge",
     "**DataFrame Merge (Join):** Combines two DataFrames on shared columns (like SQL JOIN):\n"
     "- **inner**: only rows matching in both\n"
     "- **left/right**: all rows from one side\n"
     "- **outer**: all rows from both, NaN where no match"),

    (r"\.fillna\(|\.dropna\(", "missing",
     "**Handling Missing Data:** Two strategies:\n"
     "- **Drop** (`.dropna()`): remove rows with missing values — simple but loses data\n"
     "- **Impute** (`.fillna()`): replace with mean/median/mode — preserves size but "
     "introduces assumptions\n\n"
     "Always investigate *why* data is missing before choosing."),

    # ── NLP / Tokenization ──
    (r"AutoTokenizer|tokenizer\b", "tokenizer",
     "**Tokenizer:** Converts text into numerical token IDs the model can process. "
     "Modern tokenizers use subword algorithms (BPE for GPT, WordPiece for BERT) that "
     "split unknown words into known pieces. The tokenizer must match the model."),

    (r"SentenceTransformer\(", "sbert",
     "**Sentence Transformers:** Fine-tuned transformer models that produce meaningful "
     "sentence-level embeddings. Unlike raw BERT outputs, similar sentences get "
     "similar vectors — enabling semantic search, clustering, and duplicate detection."),

    (r"cosine_similarity", "cossim",
     "**Cosine Similarity:** Measures the angle between two vectors (ignoring magnitude):\n\n"
     "$$\\cos(\\theta) = \\frac{\\mathbf{a} \\cdot \\mathbf{b}}"
     "{\\|\\mathbf{a}\\| \\, \\|\\mathbf{b}\\|}$$\n\n"
     "Range: 1.0 (identical) → 0.0 (unrelated) → -1.0 (opposite). "
     "Standard metric for comparing text embeddings."),

    (r"\bembedding\b", "embedding",
     "**Embeddings:** Dense vector representations that capture semantic meaning. "
     "Similar items map to nearby points. Unlike one-hot encoding (sparse, no similarity), "
     "embeddings enable search, clustering, and recommendation by making similarity "
     "computable as vector distance."),

    # ── Vector DBs ──
    (r"chromadb", "chroma",
     "**ChromaDB:** An open-source vector database for AI apps. Store embeddings → "
     "query with a new embedding → get the most similar results. "
     "This is the backbone of RAG (Retrieval-Augmented Generation) systems."),

    (r"qdrant", "qdrant",
     "**Qdrant:** Production-grade vector search with metadata filtering. Combines "
     "similarity search with structured queries (e.g., \"similar docs from last month\")."),

    (r"\bfaiss\b|FAISS", "faiss",
     "**FAISS:** Facebook's highly optimized similarity search library. Multiple index "
     "types with speed/accuracy/memory tradeoffs. Use for raw performance at scale."),

    # ── Visualization ──
    (r"plt\.scatter\(", "scatter",
     "**Scatter Plot:** Each dot represents one data point positioned by its x/y values. "
     "Use for: exploring relationships between features, spotting clusters, "
     "visualizing predictions vs. actuals."),

    (r"plt\.plot\(", "lineplot",
     "**Line Plot:** Connects points with lines — shows trends over a continuous variable "
     "(often time). In ML: training/validation loss curves (to detect overfitting), "
     "learning rate schedules, time series."),

    (r"plt\.hist\(", "hist",
     "**Histogram:** Shows the distribution of a single variable — reveals whether data "
     "is normal, skewed, bimodal, or has outliers. Check distributions before modeling: "
     "many algorithms assume normally distributed features."),

    (r"plt\.imshow\(", "imshow",
     "**Image Display:** Renders a 2D array as a color-coded image. Used for actual "
     "images, neural network feature maps, attention heatmaps, and correlation matrices."),

    (r"plt\.bar\(", "bar",
     "**Bar Chart:** Compares values across categories. In ML: feature importance "
     "rankings, class balance visualization, metric comparison."),

    (r"sns\.heatmap\(", "heatmap",
     "**Heatmap:** Color-coded grid showing magnitudes in a matrix. Common uses: "
     "correlation matrices (spot related features), confusion matrices (visualize "
     "classification errors), attention weights."),

    # ── Other important operations ──
    (r"np\.random\.seed|random_state", "seed",
     "**Random Seed:** Ensures reproducibility — identical random numbers every run. "
     "Critical in ML: same train/test splits, same weight initialization, same dropout "
     "masks. Without it, results vary between runs."),

    (r"gradient_descent|gradient.*step|learning_rate.*=", "gradientdescent",
     "**Gradient Descent:** The core optimization algorithm. Iteratively moves parameters "
     "downhill on the loss surface:\n\n"
     "$$\\theta_{t+1} = \\theta_t - \\eta \\, \\nabla\\mathcal{L}$$\n\n"
     "Learning rate $\\eta$ controls step size: too large → overshoots, too small → slow."),

    (r"AutoModel|AutoModelFor", "automodel",
     "**Pretrained Transformer:** Hugging Face's AutoModel loads the right architecture "
     "from a model name. Pretrained models learned language from billions of words — "
     "you fine-tune them on your task for much better results than training from scratch."),

    (r"load_dataset\(", "loadds",
     "**Hugging Face Datasets:** Loads community datasets with memory-efficient "
     "streaming and caching. Integrates directly with the Transformers training pipeline."),

    (r"openai\.", "openai",
     "**OpenAI API:** Interface to GPT and embedding models. Send prompts, get "
     "completions. Always use environment variables for API keys, implement rate "
     "limiting, and handle errors gracefully."),

    # ── Pandas operations ──
    (r"\.iloc\[|\.loc\[|\.drop\(", "indexing",
     "**DataFrame Indexing:** Access specific rows/columns:\n"
     "- `.iloc[row, col]`: integer-based (position)\n"
     "- `.loc[label, col]`: label-based (index values)\n"
     "- `.drop()`: remove rows/columns by label"),

    (r"\.describe\(\)", "describe",
     "**DataFrame.describe():** Quick statistical summary — count, mean, std, min, max, "
     "and quartiles for each numeric column. First thing to run on new data to understand "
     "ranges, detect outliers, and check for missing values."),

    (r"\.info\(\)", "info",
     "**DataFrame.info():** Shows column names, data types, non-null counts, and memory "
     "usage. Quickly reveals: which columns have missing values, which are the wrong type "
     "(e.g., numbers stored as strings), and how much memory the data uses."),

    (r"\.head\(|\.tail\(", "headtail",
     "**Preview Data:** `.head(n)` shows the first $n$ rows, `.tail(n)` the last. "
     "Always preview your data to verify it loaded correctly and understand its structure."),

    (r"\.value_counts\(\)", "valuecounts",
     "**Value Counts:** Counts unique values in a column — reveals class balance, "
     "categorical distributions, and potential data quality issues."),

    (r"\.sort_values\(", "sortvals",
     "**Sort DataFrame:** Orders rows by one or more columns. Useful for finding "
     "top/bottom values, ranking features, and preparing data for sequential analysis."),

    (r"\.apply\(|\.map\(", "apply",
     "**Apply/Map:** Apply a function to each element, row, or column. "
     "`.apply()` works on rows/columns, `.map()` on individual elements. "
     "Use for custom transformations that aren't built into Pandas."),
]


def get_topic(nb_path: str) -> str:
    """Infer topic from notebook path."""
    p = nb_path.lower()
    for pat, topic in [
        ("token", "tokenization"), ("embedding", "embeddings"),
        ("neural", "neural networks"), ("vector.*database", "vector databases"),
        (r"\brag\b", "RAG"), ("mlops", "MLOps"), ("prompt", "prompt engineering"),
        ("finetun", "LLM fine-tuning"), ("multimodal", "multimodal AI"),
        ("agent", "AI agents"), ("evaluat|metric", "model evaluation"),
        ("debug|troubleshoot", "debugging"), ("safety|redteam", "AI safety"),
        ("streaming", "real-time streaming"), ("time.series|time_series", "time series"),
        ("reinforcement|q_learn", "reinforcement learning"),
        ("causal", "causal inference"), ("deep.learn|advanced", "deep learning"),
        ("linear.algebra", "linear algebra"), ("calculus|derivative", "calculus"),
        ("probability|statistic", "statistics"), ("gradient", "optimization"),
        ("numpy", "NumPy"), ("pandas|dataframe", "Pandas"),
        ("matplotlib", "visualization"), ("scikit|sklearn", "scikit-learn"),
        ("python|crash", "Python"), ("data.science|data_science", "data science"),
        ("local.llm|ollama", "local LLMs"), ("inference.*optim", "inference optimization"),
        ("low.code|gradio|streamlit", "low-code AI"), ("math", "mathematics"),
        ("islp", "statistical learning"), ("hardware", "AI hardware"),
        ("practical", "practical data science"),
    ]:
        if re.search(pat, p):
            return topic
    return "AI/ML"


def build_explanation(code: str, topic: str) -> str:
    """Generate a rich explanation for a code cell using concept matches."""
    explanations = []
    matched_ids = set()

    for pattern, concept_id, explanation in CONCEPTS:
        if concept_id in matched_ids:
            continue
        if re.search(pattern, code):
            explanations.append(explanation)
            matched_ids.add(concept_id)

    if explanations:
        return "\n\n".join(explanations)

    # ── Fallback: analyze code structure ──
    lines = [l.strip() for l in code.split("\n") if l.strip() and not l.strip().startswith("#")]
    comments = [l.strip().lstrip("#").strip() for l in code.split("\n")
                if l.strip().startswith("#") and len(l.strip()) > 3
                and not l.strip().startswith("#!") and not l.strip().startswith("#%%")]

    has_imports = any(re.match(r"^(import|from)\s+", l) for l in code.split("\n") if l.strip())

    if has_imports:
        imports = re.findall(r"(?:from|import)\s+(\S+)", code)
        base_libs = list(dict.fromkeys(lib.split(".")[0] for lib in imports))
        parts = ["Import the libraries needed for this section:"]
        for lib in base_libs:
            parts.append(f"- **{lib}**")
        return "\n".join(parts)

    # Use comments as explanation source
    if comments:
        if len(comments) >= 2:
            return "\n".join(f"- {c}" for c in comments[:5])
        return comments[0]

    # Simple expressions
    if len(lines) == 1 and len(lines[0]) < 50:
        expr = lines[0]
        if re.match(r"^\d+\s*[\+\-\*\/\%\*]+\s*\d+$", expr):
            ops = {"+": "addition", "-": "subtraction", "*": "multiplication",
                   "/": "division", "%": "modulo (remainder)", "**": "exponentiation"}
            for sym, name in ops.items():
                if sym in expr:
                    return (f"**Python {name.title()}:** `{expr}` — Jupyter displays "
                            "the last expression's value automatically.")
        if re.match(r"^[a-zA-Z_]\w*(\.\w+)*(\(.*\))?$", expr):
            return (f"Evaluate `{expr}` — Jupyter renders the last expression as cell output.")

    # Generic fallback using topic context
    if any(re.search(r"^print\(", l) for l in code.split("\n") if l.strip()):
        return (f"Run this cell and inspect the output to verify the {topic} "
                "operations produce the expected results.")

    return (f"The code below implements the next step in this {topic} workflow. "
            "See the inline comments for details on each operation.")


def process_notebook(nb_path: Path, topic: str) -> tuple[int, int]:
    """Replace shallow explanation cells with rich ones."""
    with open(nb_path, "r", encoding="utf-8") as f:
        nb = json.load(f)

    cells = nb.get("cells", [])
    enriched = 0
    found = 0

    for i, cell in enumerate(cells):
        if cell.get("cell_type") != "markdown":
            continue

        src = cell.get("source", "")
        if isinstance(src, list):
            src = "".join(src)

        if not is_auto_generated(src):
            continue

        found += 1

        # Find the next code cell (may be i+1 or i+2)
        code_src = ""
        for j in range(i + 1, min(i + 3, len(cells))):
            if cells[j].get("cell_type") == "code":
                code_src = cells[j].get("source", "")
                if isinstance(code_src, list):
                    code_src = "".join(code_src)
                break

        if not code_src.strip():
            continue

        new_md = build_explanation(code_src, topic)
        if new_md and new_md.strip() != src.strip():
            cell["source"] = [new_md]
            enriched += 1

    if enriched > 0:
        with open(nb_path, "w", encoding="utf-8") as f:
            json.dump(nb, f, indent=1, ensure_ascii=False)
            f.write("\n")

    return enriched, found


def main():
    nbs = sorted(WORKSPACE.rglob("*.ipynb"))
    nbs = [n for n in nbs
           if ".ipynb_checkpoints" not in str(n)
           and "site/" not in str(n)
           and ".venv/" not in str(n)
           and "node_modules/" not in str(n)]

    print(f"Scanning {len(nbs)} notebooks...\n")

    total_enriched = 0
    total_found = 0
    modified = 0

    for nb_path in nbs:
        rel = str(nb_path.relative_to(WORKSPACE))
        topic = get_topic(rel)

        try:
            enriched, found = process_notebook(nb_path, topic)
            total_found += found
            if enriched > 0:
                modified += 1
                total_enriched += enriched
                print(f"  Enriched {enriched:3d}/{found:3d}: {rel}")
        except Exception as e:
            print(f"  ERROR: {rel}: {e}")

    print(f"\n{'=' * 60}")
    print(f"Enriched {total_enriched}/{total_found} cells across {modified} notebooks")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
