export default {
  "01_START_HERE": "1. Start Here",
  "02_basic_rag": "2. Basic RAG",
  "03_document_processing": "3. Document Processing",
  "04_langchain_rag": "4. LangChain RAG",
  "05_llamaindex_rag": "5. LlamaIndex RAG",
  "06_advanced_retrieval": "6. Advanced Retrieval",
  "07_conversation_rag": "7. Conversation RAG",
  "08-rag": "8. RAG",
  "08_evaluation": "9. Evaluation",
  "09_hyde_reranking": "10. HyDE Reranking",
  "10_rag_evaluation_playbook": "11. RAG Evaluation Playbook",
  "11_rag_technique_selection": "12. RAG Technique Selection",
  "12_advanced_retrieval": "13. Advanced Retrieval",
  "13_graphrag_visual_rag": "14. GraphRAG Visual RAG",
  "14_corrective_rag": "15. Corrective RAG",
  "15_parent_child_retrieval": "16. Parent Child Retrieval",
  "16_raptor_retrieval": "17. Raptor Retrieval",
  "17_assignment": "18. Assignment",
  "18_challenges": "19. Challenges",
}
