export default {
  "01_START_HERE": "1. Start Here",
  "02_basic_rag": "2. Basic Rag",
  "03_document_processing": "3. Document Processing",
  "04_langchain_rag": "4. Langchain Rag",
  "05_llamaindex_rag": "5. Llamaindex Rag",
  "06_advanced_retrieval": "6. Advanced Retrieval",
  "07_conversation_rag": "7. Conversation Rag",
  "08_evaluation": "8. Evaluation",
  "09_hyde_reranking": "9. Hyde Reranking",
  "10_rag_evaluation_playbook": "10. Rag Evaluation Playbook",
  "11_rag_technique_selection": "11. Rag Technique Selection",
  "12_advanced_retrieval": "12. Advanced Retrieval",
  "13_graphrag_visual_rag": "13. Graphrag Visual Rag",
  "14_corrective_rag": "14. Corrective Rag",
  "15_parent_child_retrieval": "15. Parent Child Retrieval",
  "16_raptor_retrieval": "16. Raptor Retrieval",
  "17_assignment": "17. Assignment",
  "18_challenges": "18. Challenges",
}
