export default {
  "analyzing-log-partition-usage": "1. Analyzing Log Partition Usage",
  "automated-archive-and-retention": "2. Automated Archive And Retention",
  "cpu-resource-management-priority": "3. Cpu Resource Management Priority",
  "debug-ssh-lockout": "4. Debug Ssh Lockout",
  "detect-memory-leak-by-monitoring-rss": "5. Detect Memory Leak By Monitoring Rss",
  "diagnose-nginx-cpu-bottleneck": "6. Diagnose Nginx Cpu Bottleneck",
  "discover-unexpected-background-jobs": "7. Discover Unexpected Background Jobs",
  "fix-inode-exhaustion-issue": "8. Fix Inode Exhaustion Issue",
  "handling-large-log-archives": "9. Handling Large Log Archives",
  "log-file-volume-assessment": "10. Log File Volume Assessment",
  "manage-service-failure-recovery": "11. Manage Service Failure Recovery",
  "managing-high-io-processes": "12. Managing High Io Processes",
  "managing-process-overload": "13. Managing Process Overload",
  "monitoring-process-ownership": "14. Monitoring Process Ownership",
  "port-conflict-resolution": "15. Port Conflict Resolution",
  "purge-empty-folders": "16. Purge Empty Folders",
  "rapid-disk-growth-on-var": "17. Rapid Disk Growth On Var",
  "real-time-log-timestamping": "18. Real Time Log Timestamping",
  "recursive-database-file-backup": "19. Recursive Database File Backup",
  "recursive-keyword-finder": "20. Recursive Keyword Finder",
  "sorted-log-aggregation": "21. Sorted Log Aggregation",
  "throttle-high-io-process": "22. Throttle High Io Process",
  "trace-process-service-ownership": "23. Trace Process Service Ownership",
  "tracing-log-file-writes": "24. Tracing Log File Writes",
  "track-forking-process-hierarchies": "25. Track Forking Process Hierarchies",
  "update-aws-configs": "26. Update Aws Configs",
  "upload-safe-file-partitioning": "27. Upload Safe File Partitioning",
  "uptime-and-load-average-audit": "28. Uptime And Load Average Audit",
  "using-unmounted-partitions": "29. Using Unmounted Partitions",
}
