export default {
  "01_START_HERE": "1. Start Here",
  "02_intro_to_agents": "2. Intro To Agents",
  "03_function_calling": "3. Function Calling",
  "04_react_pattern": "4. React Pattern",
  "05_agent_frameworks": "5. Agent Frameworks",
  "06_multi_agent_systems": "6. Multi Agent Systems",
  "07_mcp_model_context_protocol": "7. Mcp Model Context Protocol",
  "08_openai_agents_sdk_langgraph": "8. Openai Agents Sdk Langgraph",
  "09_reasoning_models": "9. Reasoning Models",
  "10_autonomous_agents_2026": "10. Autonomous Agents 2026",
  "11_agent_evaluation": "11. Agent Evaluation",
  "12_assignment": "12. Assignment",
  "12_vscode_agent_debug_logs": "13. Vscode Agent Debug Logs",
  "13_challenges": "14. Challenges",
  "14_post-quiz": "15. Post Quiz",
  "15_pre-quiz": "16. Pre Quiz",
}
