export default {
  "0.-Preamble": "1. 0. Preamble",
  "1.1-Introduction-Deep-Learning-and-ANN": "2. 1.1 Introduction Deep Learning And Ann",
  "1.2-Introduction-Theano": "3. 1.2 Introduction Theano",
  "1.3-Introduction-Keras": "4. 1.3 Introduction Keras",
  "1.4-(Extra)-A-Simple-Implementation-of-ANN-for-MNIST": "5. 1.4 (extra) A Simple Implementation Of Ann For Mnist",
  "2.1-Supervised-Learning-ConvNets": "6. 2.1 Supervised Learning Convnets",
  "2.2.1-Supervised-Learning-ConvNet-HandsOn-Part-I": "7. 2.2.1 Supervised Learning Convnet Handson Part I",
  "2.2.2-Supervised-Learning-ConvNet-HandsOn-Part-II": "8. 2.2.2 Supervised Learning Convnet Handson Part Ii",
  "2.3-Supervised-Learning-Famous-Models-with-Keras": "9. 2.3 Supervised Learning Famous Models With Keras",
  "3.1-Unsupervised-Learning-AutoEncoders-and-Embeddings": "10. 3.1 Unsupervised Learning Autoencoders And Embeddings",
  "3.2-RNN-and-LSTM": "11. 3.2 Rnn And Lstm",
  "3.3-(Extra)-LSTM-for-Sentence-Generation": "12. 3.3 (extra) Lstm For Sentence Generation",
  "4.-Conclusions": "13. 4. Conclusions",
  deep_learning_models: "14. Deep Learning Models",
  outline: "15. Outline",
}
