export default {
  "01_START_HERE": "1. Start Here",
  "02_INTERVIEW_PREP": "2. Interview Prep",
  "03_INTERVIEW_PREP_2": "3. Interview Prep 2",
  "28-practical-data-science": "4. Practical Data Science",
  "computer-vision": "5. Computer Vision",
  "deep-learning-nlp": "6. Deep Learning Nlp",
  "machine-learning": "7. Machine Learning",
  "python-data-science": "8. Python Data Science",
  "recommender-causal": "9. Recommender Causal",
  solutions: "10. Solutions",
  "sql-data-engineering": "11. Sql Data Engineering",
  "statistics-mlops": "12. Statistics Mlops",
  "time-series-forecasting": "13. Time Series Forecasting",
}
