export default {
  plot_ard: "1. Plot Ard",
  plot_bayesian_ridge_curvefit: "2. Plot Bayesian Ridge Curvefit",
  plot_elastic_net_precomputed_gram_matrix_with_weighted_samples: "3. Plot Elastic Net Precomputed Gram Matrix With Weighted Samples",
  plot_huber_vs_ridge: "4. Plot Huber Vs Ridge",
  plot_lasso_and_elasticnet: "5. Plot Lasso And Elasticnet",
  plot_lasso_dense_vs_sparse_data: "6. Plot Lasso Dense Vs Sparse Data",
  plot_lasso_lars_ic: "7. Plot Lasso Lars Ic",
  plot_lasso_lasso_lars_elasticnet_path: "8. Plot Lasso Lasso Lars Elasticnet Path",
  plot_lasso_model_selection: "9. Plot Lasso Model Selection",
  plot_logistic_l1_l2_sparsity: "10. Plot Logistic L1 L2 Sparsity",
  plot_logistic_multinomial: "11. Plot Logistic Multinomial",
  plot_logistic_path: "12. Plot Logistic Path",
  plot_multi_task_lasso_support: "13. Plot Multi Task Lasso Support",
  plot_nnls: "14. Plot Nnls",
  plot_ols_ridge: "15. Plot Ols Ridge",
  plot_omp: "16. Plot Omp",
  plot_poisson_regression_non_normal_loss: "17. Plot Poisson Regression Non Normal Loss",
  plot_polynomial_interpolation: "18. Plot Polynomial Interpolation",
  plot_quantile_regression: "19. Plot Quantile Regression",
  plot_ransac: "20. Plot Ransac",
  plot_ridge_coeffs: "21. Plot Ridge Coeffs",
  plot_ridge_path: "22. Plot Ridge Path",
  plot_robust_fit: "23. Plot Robust Fit",
  plot_sgd_early_stopping: "24. Plot Sgd Early Stopping",
  plot_sgd_iris: "25. Plot Sgd Iris",
  plot_sgd_loss_functions: "26. Plot Sgd Loss Functions",
  plot_sgd_penalties: "27. Plot Sgd Penalties",
  plot_sgd_separating_hyperplane: "28. Plot Sgd Separating Hyperplane",
  plot_sgd_weighted_samples: "29. Plot Sgd Weighted Samples",
  plot_sgdocsvm_vs_ocsvm: "30. Plot Sgdocsvm Vs Ocsvm",
  plot_sparse_logistic_regression_20newsgroups: "31. Plot Sparse Logistic Regression 20newsgroups",
  plot_sparse_logistic_regression_mnist: "32. Plot Sparse Logistic Regression Mnist",
  plot_theilsen: "33. Plot Theilsen",
  plot_tweedie_regression_insurance_claims: "34. Plot Tweedie Regression Insurance Claims",
}
