export default {
  "01_introduction": "1. Introduction",
  "02_statistical_learning": "2. Statistical Learning",
  "03_linear_regression": "3. Linear Regression",
  "04_classification": "4. Classification",
  "05_resampling_methods": "5. Resampling Methods",
  "06_regularization": "6. Regularization",
  "07_nonlinearity": "7. Nonlinearity",
  "08_tree_methods": "8. Tree Methods",
  "09_support_vector_machines": "9. Support Vector Machines",
  "10_deep_learning": "10. Deep Learning",
  "11_survival_analysis": "11. Survival Analysis",
  "12_unsupervised_learning": "12. Unsupervised Learning",
  "13_multiple_testing": "13. Multiple Testing",
  PRACTICE_EXERCISES: "14. Practice Exercises",
  "islp-book": "Overview",
  statistics_fundamentals: "16. Statistics Fundamentals",
}
