export default {
  plot_adaboost_multiclass: "1. Plot Adaboost Multiclass",
  plot_adaboost_regression: "2. Plot Adaboost Regression",
  plot_adaboost_twoclass: "3. Plot Adaboost Twoclass",
  plot_bias_variance: "4. Plot Bias Variance",
  plot_ensemble_oob: "5. Plot Ensemble Oob",
  plot_feature_transformation: "6. Plot Feature Transformation",
  plot_forest_hist_grad_boosting_comparison: "7. Plot Forest Hist Grad Boosting Comparison",
  plot_forest_importances: "8. Plot Forest Importances",
  plot_forest_iris: "9. Plot Forest Iris",
  plot_gradient_boosting_categorical: "10. Plot Gradient Boosting Categorical",
  plot_gradient_boosting_early_stopping: "11. Plot Gradient Boosting Early Stopping",
  plot_gradient_boosting_oob: "12. Plot Gradient Boosting Oob",
  plot_gradient_boosting_quantile: "13. Plot Gradient Boosting Quantile",
  plot_gradient_boosting_regression: "14. Plot Gradient Boosting Regression",
  plot_gradient_boosting_regularization: "15. Plot Gradient Boosting Regularization",
  plot_hgbt_regression: "16. Plot Hgbt Regression",
  plot_isolation_forest: "17. Plot Isolation Forest",
  plot_monotonic_constraints: "18. Plot Monotonic Constraints",
  plot_random_forest_embedding: "19. Plot Random Forest Embedding",
  plot_random_forest_regression_multioutput: "20. Plot Random Forest Regression Multioutput",
  plot_stack_predictors: "21. Plot Stack Predictors",
  plot_voting_decision_regions: "22. Plot Voting Decision Regions",
  plot_voting_regressor: "23. Plot Voting Regressor",
}
