export default {
  "01_START_HERE": "1. Start Here",
  "02_mlops_cheatsheet": "2. MLOps Cheatsheet",
  "03_ai_cloud_services_cheatsheet": "3. AI Cloud Services Cheatsheet",
  "04_gpu_compute_cheatsheet": "4. Gpu Compute Cheatsheet",
  "05_ml_model_serving_cheatsheet": "5. ML Model Serving Cheatsheet",
  "06_experiment_tracking_cheatsheet": "6. Experiment Tracking Cheatsheet",
  "07_data_pipelines_cheatsheet": "7. Data Pipelines Cheatsheet",
  "ai-cloud-services-cheatsheet": "8. AI Cloud Services Cheatsheet",
  "ai-ml": "9. AI ML",
  "data-pipelines-cheatsheet": "10. Data Pipelines Cheatsheet",
  "experiment-tracking-cheatsheet": "11. Experiment Tracking Cheatsheet",
  "gpu-compute-cheatsheet": "12. Gpu Compute Cheatsheet",
  "ml-model-serving-cheatsheet": "13. ML Model Serving Cheatsheet",
  "mlops-cheatsheet": "14. MLOps Cheatsheet",
}
