export default {
  "01_START_HERE": "1. Start Here",
  "02_mlops_cheatsheet": "2. Mlops Cheatsheet",
  "03_ai_cloud_services_cheatsheet": "3. Ai Cloud Services Cheatsheet",
  "04_gpu_compute_cheatsheet": "4. Gpu Compute Cheatsheet",
  "05_ml_model_serving_cheatsheet": "5. Ml Model Serving Cheatsheet",
  "06_experiment_tracking_cheatsheet": "6. Experiment Tracking Cheatsheet",
  "07_data_pipelines_cheatsheet": "7. Data Pipelines Cheatsheet",
  "ai-cloud-services-cheatsheet": "8. Ai Cloud Services Cheatsheet",
  "data-pipelines-cheatsheet": "9. Data Pipelines Cheatsheet",
  "experiment-tracking-cheatsheet": "10. Experiment Tracking Cheatsheet",
  "gpu-compute-cheatsheet": "11. Gpu Compute Cheatsheet",
  "ml-model-serving-cheatsheet": "12. Ml Model Serving Cheatsheet",
  "mlops-cheatsheet": "13. Mlops Cheatsheet",
}
