export default {
  plot_cyclical_feature_engineering: "1. Plot Cyclical Feature Engineering",
  plot_digits_denoising: "2. Plot Digits Denoising",
  plot_face_recognition: "3. Plot Face Recognition",
  plot_model_complexity_influence: "4. Plot Model Complexity Influence",
  plot_out_of_core_classification: "5. Plot Out Of Core Classification",
  plot_outlier_detection_wine: "6. Plot Outlier Detection Wine",
  plot_prediction_latency: "7. Plot Prediction Latency",
  plot_species_distribution_modeling: "8. Plot Species Distribution Modeling",
  plot_stock_market: "9. Plot Stock Market",
  plot_time_series_lagged_features: "10. Plot Time Series Lagged Features",
  plot_tomography_l1_reconstruction: "11. Plot Tomography L1 Reconstruction",
  plot_topics_extraction_with_nmf_lda: "12. Plot Topics Extraction With Nmf Lda",
  wikipedia_principal_eigenvector: "13. Wikipedia Principal Eigenvector",
}
